# Machine Learning With Spark ML
In this lab assignment, you will complete a project by going through the following steps:
1. Get the data.
2. Discover the data to gain insights.
3. Prepare the data for Machine Learning algorithms.
4. Select a model and train it.
5. Fine-tune your model.
6. Present your solution.

As a dataset, we use the California Housing Prices dataset from the StatLib repository. This dataset was based on data from the 1990 California census. The dataset has the following columns
1. `longitude`: a measure of how far west a house is (a higher value is farther west)
2. `latitude`: a measure of how far north a house is (a higher value is farther north)
3. `housing_,median_age`: median age of a house within a block (a lower number is a newer building)
4. `total_rooms`: total number of rooms within a block
5. `total_bedrooms`: total number of bedrooms within a block
6. `population`: total number of people residing within a block
7. `households`: total number of households, a group of people residing within a home unit, for a block
8. `median_income`: median income for households within a block of houses
9. `median_house_value`: median house value for households within a block
10. `ocean_proximity`: location of the house w.r.t ocean/sea

---
# 1. Get the data
Let's start the lab by loading the dataset. The can find the dataset at `data/housing.csv`. To infer column types automatically, when you are reading the file, you need to set `inferSchema` to true. Moreover enable the `header` option to read the columns' name from the file.

In [1]:
// TODO: Replace <FILL IN> with appropriate code

val housing = spark.read.format("csv").option("inferSchema", "true").option("header", "true").load("data/housing.csv")

housing = [longitude: double, latitude: double ... 8 more fields]


[longitude: double, latitude: double ... 8 more fields]

Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting

Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting

Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting

Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting

Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting

Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting

Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting
Predicting

---
# 2. Discover the data to gain insights
Now it is time to take a look at the data. In this step we are going to take a look at the data a few different ways:
* See the schema and dimension of the dataset
* Look at the data itself
* Statistical summary of the attributes
* Breakdown of the data by the categorical attribute variable
* Find the correlation among different attributes
* Make new attributes by combining existing attributes

## 2.1. Schema and dimension
Print the schema of the dataset

In [2]:
// TODO: Replace <FILL IN> with appropriate code

housing.printSchema()

root
 |-- longitude: double (nullable = true)
 |-- latitude: double (nullable = true)
 |-- housing_median_age: double (nullable = true)
 |-- total_rooms: double (nullable = true)
 |-- total_bedrooms: double (nullable = true)
 |-- population: double (nullable = true)
 |-- households: double (nullable = true)
 |-- median_income: double (nullable = true)
 |-- median_house_value: double (nullable = true)
 |-- ocean_proximity: string (nullable = true)



Print the number of records in the dataset.

In [3]:
// TODO: Replace <FILL IN> with appropriate code

housing.count()

20640

## 2.2. Look at the data
Print the first five records of the dataset.

In [4]:
// TODO: Replace <FILL IN> with appropriate code

housing.head(5)

Array([-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY], [-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY], [-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY], [-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY], [-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY])

Print the number of records with population more than 10000.

In [5]:
// TODO: Replace <FILL IN> with appropriate code

housing.where("population > 10000").count()

23

## 2.3. Statistical summary
Print a summary of the table statistics for the attributes `housing_median_age`, `total_rooms`, `median_house_value`, and `population`. You can use the `describe` command.

In [6]:
// TODO: Replace <FILL IN> with appropriate code

housing.describe().show()

+-------+-------------------+-----------------+------------------+------------------+------------------+------------------+-----------------+------------------+------------------+---------------+
|summary|          longitude|         latitude|housing_median_age|       total_rooms|    total_bedrooms|        population|       households|     median_income|median_house_value|ocean_proximity|
+-------+-------------------+-----------------+------------------+------------------+------------------+------------------+-----------------+------------------+------------------+---------------+
|  count|              20640|            20640|             20640|             20640|             20433|             20640|            20640|             20640|             20640|          20640|
|   mean|-119.56970445736148| 35.6318614341087|28.639486434108527|2635.7630813953488| 537.8705525375618|1425.4767441860465|499.5396802325581|3.8706710029070246|206855.81690891474|           null|
| stddev|  2.0035317

Print the maximum age (`housing_median_age`), the minimum number of rooms (`total_rooms`), and the average of house values (`median_house_value`).

In [7]:
// TODO: Replace <FILL IN> with appropriate code

import org.apache.spark.sql.functions._

housing.select(max("housing_median_age"), min("total_rooms"), avg("median_house_value")).show()

+-----------------------+----------------+-----------------------+
|max(housing_median_age)|min(total_rooms)|avg(median_house_value)|
+-----------------------+----------------+-----------------------+
|                   52.0|             2.0|     206855.81690891474|
+-----------------------+----------------+-----------------------+



## 2.4. Breakdown the data by categorical data
Print the number of houses in different areas (`ocean_proximity`), and sort them in descending order.

In [8]:
// TODO: Replace <FILL IN> with appropriate code

housing.groupBy("ocean_proximity").count().sort(desc("count")).show()

+---------------+-----+
|ocean_proximity|count|
+---------------+-----+
|      <1H OCEAN| 9136|
|         INLAND| 6551|
|     NEAR OCEAN| 2658|
|       NEAR BAY| 2290|
|         ISLAND|    5|
+---------------+-----+



Print the average value of the houses (`median_house_value`) in different areas (`ocean_proximity`), and call the new column `avg_value` when print it.

In [9]:
// TODO: Replace <FILL IN> with appropriate code

housing.groupBy("ocean_proximity").agg(avg("median_house_value").alias("avg_value")).show()

+---------------+------------------+
|ocean_proximity|         avg_value|
+---------------+------------------+
|         ISLAND|          380440.0|
|     NEAR OCEAN|249433.97742663656|
|       NEAR BAY|259212.31179039303|
|      <1H OCEAN|240084.28546409807|
|         INLAND|124805.39200122119|
+---------------+------------------+



Rewrite the above question in SQL.

In [10]:
// TODO: Replace <FILL IN> with appropriate code

housing.createOrReplaceTempView("df")
spark.sql("SELECT ocean_proximity, avg(median_house_value) AS avg_value FROM df GROUP BY ocean_proximity").show()

+---------------+------------------+
|ocean_proximity|         avg_value|
+---------------+------------------+
|         ISLAND|          380440.0|
|     NEAR OCEAN|249433.97742663656|
|       NEAR BAY|259212.31179039303|
|      <1H OCEAN|240084.28546409807|
|         INLAND|124805.39200122119|
+---------------+------------------+



## 2.5. Correlation among attributes
Print the correlation among the attributes `housing_median_age`, `total_rooms`, `median_house_value`, and `population`. To do so, first you need to put these attributes into one vector. Then, compute the standard correlation coefficient (Pearson) between every pair of attributes in this new vector. To make a vector of these attributes, you can use the `VectorAssembler` Transformer.

In [11]:
// TODO: Replace <FILL IN> with appropriate code

import org.apache.spark.ml.feature.VectorAssembler

val va = new VectorAssembler().setInputCols(Array("housing_median_age", "total_rooms", "median_house_value", "population")).setOutputCol("attributes")

val housingAttrs = va.transform(housing)

housingAttrs.show(5)

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+--------------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|ocean_proximity|          attributes|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------+--------------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|          452600.0|       NEAR BAY|[41.0,880.0,45260...|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|          358500.0|       NEAR BAY|[21.0,7099.0,3585...|
|  -122.24|   37.85|              52.0|     1467.0|         190.0|     496.0|     177.0|       7.2574|          352100.0|       NEAR BAY|[52.0,1467.0,3521...|
|  -122.25|   37.85|              52.0|     12

va = vecAssembler_0ac7378316d6
housingAttrs = [longitude: double, latitude: double ... 9 more fields]


[longitude: double, latitude: double ... 9 more fields]

In [12]:
// TODO: Replace <FILL IN> with appropriate code

import org.apache.spark.ml.linalg.Matrix
import org.apache.spark.ml.stat.Correlation
import org.apache.spark.sql.Row

val Row(coeff: Matrix) = Correlation.corr(housingAttrs, "attributes").head

println(s"The standard correlation coefficient:\n ${coeff}")

The standard correlation coefficient:
 1.0                   -0.36126220122231784  0.10562341249318154   -0.2962442397735293   
-0.36126220122231784  1.0                   0.13415311380654338   0.8571259728659772    
0.10562341249318154   0.13415311380654338   1.0                   -0.02464967888891235  
-0.2962442397735293   0.8571259728659772    -0.02464967888891235  1.0                   


coeff = 


1.0                   -0.36126220122231784  0.10562341249318154   -0.2962442397735293
-0.36126220122231784  1.0                   0.13415311380654338   0.8571259728659772
0.10562341249318154   0.13415311380654338   1.0                   -0.02464967888891235
-0.2962442397735293   0.8571259728659772    -0.02464967888891235  1.0


## 2.6. Combine and make new attributes
Now, let's try out various attribute combinations. In the given dataset, the total number of rooms in a block is not very useful, if we don't know how many households there are. What we really want is the number of rooms per household. Similarly, the total number of bedrooms by itself is not very useful, and we want to compare it to the number of rooms. And the population per household seems like also an interesting attribute combination to look at. To do so, add the three new columns to the dataset as below. We will call the new dataset the `housingExtra`.
```
rooms_per_household = total_rooms / households
bedrooms_per_room = total_bedrooms / total_rooms
population_per_household = population / households
```

In [13]:
// TODO: Replace <FILL IN> with appropriate code

val housingCol1 = housing.withColumn("rooms_per_household", housing("total_rooms") / housing("households"))

val housingCol2 = housingCol1.withColumn("bedrooms_per_room", housingCol1("total_bedrooms") / housingCol1("total_rooms"))

val housingExtra = housingCol2.withColumn("population_per_household", housingCol2("population") / housingCol2("households"))

housingExtra.select("rooms_per_household", "bedrooms_per_room", "population_per_household").show(5)

+-------------------+-------------------+------------------------+
|rooms_per_household|  bedrooms_per_room|population_per_household|
+-------------------+-------------------+------------------------+
|  6.984126984126984|0.14659090909090908|      2.5555555555555554|
|  6.238137082601054|0.15579659106916466|       2.109841827768014|
|  8.288135593220339|0.12951601908657123|      2.8022598870056497|
| 5.8173515981735155|0.18445839874411302|       2.547945205479452|
|  6.281853281853282| 0.1720958819913952|      2.1814671814671813|
+-------------------+-------------------+------------------------+
only showing top 5 rows



housingCol1 = [longitude: double, latitude: double ... 9 more fields]
housingCol2 = [longitude: double, latitude: double ... 10 more fields]
housingExtra = [longitude: double, latitude: double ... 11 more fields]


[longitude: double, latitude: double ... 11 more fields]

---
## 3. Prepare the data for Machine Learning algorithms
Before going through the Machine Learning steps, let's first rename the label column from `median_house_value` to `label`.

In [14]:
// TODO: Replace <FILL IN> with appropriate code

val renamedHousing = housingExtra.withColumnRenamed("median_house_value", "label")

renamedHousing = [longitude: double, latitude: double ... 11 more fields]


[longitude: double, latitude: double ... 11 more fields]

Now, we want to separate the numerical attributes from the categorical attribute (`ocean_proximity`) and keep their column names in two different lists. Moreover, sice we don't want to apply the same transformations to the predictors (features) and the label, we should remove the label attribute from the list of predictors. 

In [15]:
// label columns
val colLabel = "label"

// categorical columns
val colCat = "ocean_proximity"

// numerical columns
val colNum = renamedHousing.columns.filter(_ != colLabel).filter(_ != colCat)

colLabel = label
colCat = ocean_proximity
colNum = Array(longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, households, median_income, rooms_per_household, bedrooms_per_room, population_per_household)


Array(longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, households, median_income, rooms_per_household, bedrooms_per_room, population_per_household)

## 3.1. Prepare continuse attributes
### Data cleaning
Most Machine Learning algorithms cannot work with missing features, so we should take care of them. As a first step, let's find the columns with missing values in the numerical attributes. To do so, we can print the number of missing values of each continues attributes, listed in `colNum`.

In [16]:
// TODO: Replace <FILL IN> with appropriate code

for (c <- colNum) {
    val cnt = renamedHousing.filter(renamedHousing(c).isNull || 
                                    renamedHousing(c) === "").count
    println(s"${cnt} number of missing vals in ${c}")
}

0 number of missing vals in longitude
0 number of missing vals in latitude
0 number of missing vals in housing_median_age
0 number of missing vals in total_rooms
207 number of missing vals in total_bedrooms
0 number of missing vals in population
0 number of missing vals in households
0 number of missing vals in median_income
0 number of missing vals in rooms_per_household
207 number of missing vals in bedrooms_per_room
0 number of missing vals in population_per_household


As we observerd above, the `total_bedrooms` and `bedrooms_per_room` attributes have some missing values. One way to take care of missing values is to use the `Imputer` Transformer, which completes missing values in a dataset, either using the mean or the median of the columns in which the missing values are located. To use it, you need to create an `Imputer` instance, specifying that you want to replace each attribute's missing values with the "median" of that attribute.

In [17]:
// TODO: Replace <FILL IN> with appropriate code

import org.apache.spark.ml.feature.Imputer

val imputer = new Imputer().setStrategy("median").setInputCols(Array("total_bedrooms", "bedrooms_per_room")).
    setOutputCols(Array("total_bedrooms", "bedrooms_per_room"))                           
val imputedHousing = imputer.fit(renamedHousing).transform(renamedHousing)

imputedHousing.select("total_bedrooms", "bedrooms_per_room").show(5)

+--------------+-------------------+
|total_bedrooms|  bedrooms_per_room|
+--------------+-------------------+
|         129.0|0.14659090909090908|
|        1106.0|0.15579659106916466|
|         190.0|0.12951601908657123|
|         235.0|0.18445839874411302|
|         280.0| 0.1720958819913952|
+--------------+-------------------+
only showing top 5 rows



imputer = imputer_808a34db605f
imputedHousing = [longitude: double, latitude: double ... 11 more fields]


[longitude: double, latitude: double ... 11 more fields]

### Scaling
One of the most important transformations you need to apply to your data is feature scaling. With few exceptions, Machine Learning algorithms don't perform well when the input numerical attributes have very different scales. This is the case for the housing data: the total number of rooms ranges from about 6 to 39,320, while the median incomes only range from 0 to 15. Note that scaling the label attribues is generally not required.

One way to get all attributes to have the same scale is to use standardization. In standardization, for each value, first it subtracts the mean value (so standardized values always have a zero mean), and then it divides by the variance so that the resulting distribution has unit variance. To do this, we can use the `StandardScaler` Estimator. To use `StandardScaler`, again we need to convert all the numerical attributes into a big vectore of features using `VectorAssembler`, and then call `StandardScaler` on that vactor.

In [18]:
imputedHousing.printSchema

root
 |-- longitude: double (nullable = true)
 |-- latitude: double (nullable = true)
 |-- housing_median_age: double (nullable = true)
 |-- total_rooms: double (nullable = true)
 |-- total_bedrooms: double (nullable = true)
 |-- population: double (nullable = true)
 |-- households: double (nullable = true)
 |-- median_income: double (nullable = true)
 |-- label: double (nullable = true)
 |-- ocean_proximity: string (nullable = true)
 |-- rooms_per_household: double (nullable = true)
 |-- bedrooms_per_room: double (nullable = true)
 |-- population_per_household: double (nullable = true)



In [19]:
// TODO: Replace <FILL IN> with appropriate code

import org.apache.spark.ml.feature.{VectorAssembler, StandardScaler}

val va = new VectorAssembler().setInputCols(colNum).setOutputCol("forscaling")
val featuredHousing = va.transform(imputedHousing)
// Q: does false mean substract mean here?????
val scaler = new StandardScaler().setInputCol("forscaling").setOutputCol("scaled").setWithStd(true).setWithMean(true)
val scaledHousing = scaler.fit(featuredHousing).transform(featuredHousing)

scaledHousing.show(5)

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+--------+---------------+-------------------+-------------------+------------------------+--------------------+--------------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|   label|ocean_proximity|rooms_per_household|  bedrooms_per_room|population_per_household|          forscaling|              scaled|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+--------+---------------+-------------------+-------------------+------------------------+--------------------+--------------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|452600.0|       NEAR BAY|  6.984126984126984|0.14659090909090908|      2.5555555555555554|[-122.23,37.88,41...|[-1.3278030546902...|
|  -122.22|   37.86|              21.0|     7099.0|        1

va = vecAssembler_cea608bd66e3
featuredHousing = [longitude: double, latitude: double ... 12 more fields]
scaler = stdScal_bb1309ee33a3
scaledHousing = [longitude: double, latitude: double ... 13 more fields]


[longitude: double, latitude: double ... 13 more fields]

## 3.2. Prepare categorical attributes
After imputing and scaling the continuse attributes, we should take care of the categorical attributes. Let's first print the number of distict values of the categirical attribute `ocean_proximity`.

In [20]:
// TODO: Replace <FILL IN> with appropriate code

renamedHousing.select("ocean_proximity").distinct.show

+---------------+
|ocean_proximity|
+---------------+
|         ISLAND|
|     NEAR OCEAN|
|       NEAR BAY|
|      <1H OCEAN|
|         INLAND|
+---------------+



### String indexer
Most Machine Learning algorithms prefer to work with numbers. So let's convert the categorical attribute `ocean_proximity` to numbers. To do so, we can use the `StringIndexer` that encodes a string column of labels to a column of label indices. The indices are in [0, numLabels), ordered by label frequencies, so the most frequent label gets index 0.

In [21]:
// TODO: Replace <FILL IN> with appropriate code

import org.apache.spark.ml.feature.StringIndexer

val indexer = new StringIndexer().setInputCol("ocean_proximity").setOutputCol("ocean_proximity_Index")
val idxHousing = indexer.fit(renamedHousing).transform(renamedHousing)

idxHousing.show(5)

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+--------+---------------+-------------------+-------------------+------------------------+---------------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|   label|ocean_proximity|rooms_per_household|  bedrooms_per_room|population_per_household|ocean_proximity_Index|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+--------+---------------+-------------------+-------------------+------------------------+---------------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|452600.0|       NEAR BAY|  6.984126984126984|0.14659090909090908|      2.5555555555555554|                  3.0|
|  -122.22|   37.86|              21.0|     7099.0|        1106.0|    2401.0|    1138.0|       8.3014|358500.0|       NEAR BAY|  6.238137082

indexer = strIdx_7dcb0d9f6628
idxHousing = [longitude: double, latitude: double ... 12 more fields]


[longitude: double, latitude: double ... 12 more fields]

Now we can use this numerical data in any Machine Learning algorithm. You can look at the mapping that this encoder has learned using the `labels` method: "<1H OCEAN" is mapped to 0, "INLAND" is mapped to 1, etc.

In [22]:
indexer.fit(renamedHousing).labels

Array(<1H OCEAN, INLAND, NEAR OCEAN, NEAR BAY, ISLAND)

### One-hot encoding
Now, convert the label indices built in the last step into one-hot vectors. To do this, you can take advantage of the `OneHotEncoderEstimator` Estimator.

In [23]:
// TODO: Replace <FILL IN> with appropriate code

import org.apache.spark.ml.feature.OneHotEncoderEstimator

val encoder = new OneHotEncoderEstimator().setInputCols(Array("ocean_proximity_Index")).setOutputCols(Array("ocean_proximity_Encoded"))
val ohHousing = encoder.fit(idxHousing).transform(idxHousing)

ohHousing.show(5)

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+--------+---------------+-------------------+-------------------+------------------------+---------------------+-----------------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|   label|ocean_proximity|rooms_per_household|  bedrooms_per_room|population_per_household|ocean_proximity_Index|ocean_proximity_Encoded|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+--------+---------------+-------------------+-------------------+------------------------+---------------------+-----------------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|452600.0|       NEAR BAY|  6.984126984126984|0.14659090909090908|      2.5555555555555554|                  3.0|          (4,[3],[1.0])|
|  -122.22|   37.86|              21.0|     

encoder = oneHotEncoder_1a2cba7ce47e
ohHousing = [longitude: double, latitude: double ... 13 more fields]


[longitude: double, latitude: double ... 13 more fields]

---
# 4. Pipeline
As you can see, there are many data transformation steps that need to be executed in the right order. For example, you called the `Imputer`, `VectorAssembler`, and `StandardScaler` from left to right. However, we can use the `Pipeline` class to define a sequence of Transformers/Estimators, and run them in order. A `Pipeline` is an `Estimator`, thus, after a Pipeline's `fit()` method runs, it produces a `PipelineModel`, which is a `Transformer`.

Now, let's create a pipeline called `numPipeline` to call the numerical transformers you built above (`imputer`, `va`, and `scaler`) in the right order from left to right, as well as a pipeline called `catPipeline` to call the categorical transformers (`indexer` and `encoder`). Then, put these two pipelines `numPipeline` and `catPipeline` into one pipeline.

In [24]:
// TODO: Replace <FILL IN> with appropriate code

import org.apache.spark.ml.{Pipeline, PipelineModel, PipelineStage}

val numPipeline = new Pipeline().setStages(Array(imputer, va, scaler))
val catPipeline = new Pipeline().setStages(Array(indexer, encoder))
val pipeline = new Pipeline().setStages(Array(numPipeline, catPipeline))
val newHousing = pipeline.fit(renamedHousing).transform(renamedHousing)

newHousing.show(5)

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+--------+---------------+-------------------+-------------------+------------------------+--------------------+--------------------+---------------------+-----------------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|   label|ocean_proximity|rooms_per_household|  bedrooms_per_room|population_per_household|          forscaling|              scaled|ocean_proximity_Index|ocean_proximity_Encoded|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+--------+---------------+-------------------+-------------------+------------------------+--------------------+--------------------+---------------------+-----------------------+
|  -122.23|   37.88|              41.0|      880.0|         129.0|     322.0|     126.0|       8.3252|452600.0|       NEAR BAY|  6.984126984126984|0.14659090

numPipeline = pipeline_fd43b3de829d
catPipeline = pipeline_7a62dbc4b9c8
pipeline = pipeline_e1186758ecfc
newHousing = [longitude: double, latitude: double ... 15 more fields]


[longitude: double, latitude: double ... 15 more fields]

In [25]:
newHousing.printSchema

root
 |-- longitude: double (nullable = true)
 |-- latitude: double (nullable = true)
 |-- housing_median_age: double (nullable = true)
 |-- total_rooms: double (nullable = true)
 |-- total_bedrooms: double (nullable = true)
 |-- population: double (nullable = true)
 |-- households: double (nullable = true)
 |-- median_income: double (nullable = true)
 |-- label: double (nullable = true)
 |-- ocean_proximity: string (nullable = true)
 |-- rooms_per_household: double (nullable = true)
 |-- bedrooms_per_room: double (nullable = true)
 |-- population_per_household: double (nullable = true)
 |-- forscaling: vector (nullable = true)
 |-- scaled: vector (nullable = true)
 |-- ocean_proximity_Index: double (nullable = false)
 |-- ocean_proximity_Encoded: vector (nullable = true)



Now, use `VectorAssembler` to put all attributes of the final dataset `newHousing` into a big vector, and call the new column `features`.

In [26]:
// TODO: Replace <FILL IN> with appropriate code

val va2 = new VectorAssembler().setInputCols(Array("scaled", "ocean_proximity_Encoded")).setOutputCol("features")
val dataset = va2.transform(newHousing).select("features", "label")

dataset.show(5)

+--------------------+--------+
|            features|   label|
+--------------------+--------+
|[-1.3278030546902...|452600.0|
|[-1.3228118684350...|358500.0|
|[-1.3327942409452...|352100.0|
|[-1.3377854272003...|341300.0|
|[-1.3377854272003...|342200.0|
+--------------------+--------+
only showing top 5 rows



va2 = vecAssembler_781fd152d26d
dataset = [features: vector, label: double]


[features: vector, label: double]

---
# 5. Make a model
Here we going to make four different regression models:
* Linear regression model
* Decission tree regression
* Random forest regression
* Gradient-booster forest regression

But, before giving the data to train a Machine Learning model, let's first split the data into training dataset (`trainSet`) with 80% of the whole data, and test dataset (`testSet`) with 20% of it.

In [27]:
// TODO: Replace <FILL IN> with appropriate code

val Array(trainSet, testSet) = dataset.randomSplit(Array(0.8, 0.2))

trainSet = [features: vector, label: double]
testSet = [features: vector, label: double]


[features: vector, label: double]

## 5.1. Linear regression model
Now, train a Linear Regression model using the `LinearRegression` class. Then, print the coefficients and intercept of the model, as well as the summary of the model over the training set by calling the `summary` method.

In [28]:
// TODO: Replace <FILL IN> with appropriate code

import org.apache.spark.ml.regression.LinearRegression

// train the model
val lr = new LinearRegression().setFeaturesCol("features").setLabelCol("label")
val lrModel = lr.fit(trainSet)
val trainingSummary = lrModel.summary

println(s"Coefficients: ${lrModel.coefficients}, Intercept: ${lrModel.intercept}")
println(s"RMSE: ${trainingSummary.rootMeanSquaredError}")

Coefficients: [-56268.580836577545,-56504.52821536907,13645.664396936429,5946.267532689931,3828.6511194285454,-45049.769010833865,40578.845661271596,78168.6190774182,6713.191037755801,15954.560140382999,-712.3007263722913,-176355.83239405608,-211030.6939497782,-172468.15905241386,-180988.64532551018], Intercept: 394462.5157478082
RMSE: 68402.21973943154


lr = linReg_c2051380ebef
lrModel = linReg_c2051380ebef
trainingSummary = org.apache.spark.ml.regression.LinearRegressionTrainingSummary@7e98f60e


org.apache.spark.ml.regression.LinearRegressionTrainingSummary@7e98f60e

Now, use `RegressionEvaluator` to measure the root-mean-square-erroe (RMSE) of the model on the test dataset.

In [29]:
// TODO: Replace <FILL IN> with appropriate code

import org.apache.spark.ml.evaluation.RegressionEvaluator

// make predictions on the test data
val predictions = lrModel.transform(testSet)
predictions.select("prediction", "label", "features").show(5)

// select (prediction, true label) and compute test error.
val evaluator = new RegressionEvaluator().setLabelCol("label").setPredictionCol("prediction").setMetricName("rmse")
val rmse = evaluator.evaluate(predictions)
println(s"Root Mean Squared Error (RMSE) on test data = $rmse")

+------------------+--------+--------------------+
|        prediction|   label|            features|
+------------------+--------+--------------------+
|199035.89127791065|128900.0|[-2.2960931881793...|
| 135536.2723507936| 68300.0|[-2.2960931881793...|
| 156173.9987570073| 70500.0|[-2.2960931881793...|
|192540.33553536574| 60000.0|[-2.2960931881793...|
|181648.65486894012| 85400.0|[-2.2911020019242...|
+------------------+--------+--------------------+
only showing top 5 rows

Root Mean Squared Error (RMSE) on test data = 65908.14659883764


predictions = [features: vector, label: double ... 1 more field]
evaluator = regEval_c9c759ce6e0f
rmse = 65908.14659883764


65908.14659883764

## 5.2. Decision tree regression
Repeat what you have done on Regression Model to build a Decision Tree model. Use the `DecisionTreeRegressor` to make a model and then measure its RMSE on the test dataset.

In [30]:
// TODO: Replace <FILL IN> with appropriate code

import org.apache.spark.ml.regression.DecisionTreeRegressor
import org.apache.spark.ml.evaluation.RegressionEvaluator

val dt = new DecisionTreeRegressor().setLabelCol("label").setFeaturesCol("features")

// train the model
val dtModel = dt.fit(trainSet)

// make predictions on the test data
val predictions = dtModel.transform(testSet)
predictions.select("prediction", "label", "features").show(5)

// select (prediction, true label) and compute test error
val evaluator = new RegressionEvaluator().setLabelCol("label").setPredictionCol("prediction").setMetricName("rmse")
val rmse = evaluator.evaluate(predictions)
println(s"Root Mean Squared Error (RMSE) on test data = $rmse")

+------------------+--------+--------------------+
|        prediction|   label|            features|
+------------------+--------+--------------------+
|238837.70785340315|128900.0|[-2.2960931881793...|
|  138305.223880597| 68300.0|[-2.2960931881793...|
|  138305.223880597| 70500.0|[-2.2960931881793...|
|  138305.223880597| 60000.0|[-2.2960931881793...|
|  138305.223880597| 85400.0|[-2.2911020019242...|
+------------------+--------+--------------------+
only showing top 5 rows

Root Mean Squared Error (RMSE) on test data = 64983.61520854657


dt = dtr_f20e304746d9
dtModel = DecisionTreeRegressionModel (uid=dtr_f20e304746d9) of depth 5 with 63 nodes
predictions = [features: vector, label: double ... 1 more field]
evaluator = regEval_0a5518afc4ab
rmse = 64983.61520854657


64983.61520854657

## 5.3. Random forest regression
Let's try the test error on a Random Forest Model. Youcan use the `RandomForestRegressor` to make a Random Forest model.

In [31]:
// TODO: Replace <FILL IN> with appropriate code

import org.apache.spark.ml.regression.RandomForestRegressor
import org.apache.spark.ml.evaluation.RegressionEvaluator

val rf = new RandomForestRegressor().setLabelCol("label").setFeaturesCol("features")

// train the model
val rfModel = rf.fit(trainSet)

// make predictions on the test data
val predictions = rfModel.transform(testSet)
predictions.select("prediction", "label", "features").show(5)

// select (prediction, true label) and compute test error
val evaluator = new RegressionEvaluator().setLabelCol("label").setPredictionCol("prediction").setMetricName("rmse")
val rmse = evaluator.evaluate(predictions)
println(s"Root Mean Squared Error (RMSE) on test data = $rmse")

+------------------+--------+--------------------+
|        prediction|   label|            features|
+------------------+--------+--------------------+
|237236.20288785064|128900.0|[-2.2960931881793...|
|154855.06738434287| 68300.0|[-2.2960931881793...|
|154968.81558458498| 70500.0|[-2.2960931881793...|
|171363.58618735167| 60000.0|[-2.2960931881793...|
|181381.43342153725| 85400.0|[-2.2911020019242...|
+------------------+--------+--------------------+
only showing top 5 rows

Root Mean Squared Error (RMSE) on test data = 63374.67224818564


rf = rfr_064687d07a5a
rfModel = RandomForestRegressionModel (uid=rfr_064687d07a5a) with 20 trees
predictions = [features: vector, label: double ... 1 more field]
evaluator = regEval_937be0532f94
rmse = 63374.67224818564


63374.67224818564

## 5.4. Gradient-boosted tree regression
Fianlly, we want to build a Gradient-boosted Tree Regression model and test the RMSE of the test data. Use the `GBTRegressor` to build the model.

In [32]:
// TODO: Replace <FILL IN> with appropriate code

import org.apache.spark.ml.regression.GBTRegressor
import org.apache.spark.ml.evaluation.RegressionEvaluator

val gb = new GBTRegressor().setLabelCol("label").setFeaturesCol("features")

// train the model
val gbModel = gb.fit(trainSet)

// make predictions on the test data
val predictions = gbModel.transform(testSet)
predictions.select("prediction", "label", "features").show(5)

// select (prediction, true label) and compute test error
val evaluator = new RegressionEvaluator().setLabelCol("label").setPredictionCol("prediction").setMetricName("rmse")
val rmse = evaluator.evaluate(predictions)
println(s"Root Mean Squared Error (RMSE) on test data = $rmse")

+------------------+--------+--------------------+
|        prediction|   label|            features|
+------------------+--------+--------------------+
|170078.31955559124|128900.0|[-2.2960931881793...|
| 91378.25437971574| 68300.0|[-2.2960931881793...|
| 81954.41405478901| 70500.0|[-2.2960931881793...|
|131918.93998127076| 60000.0|[-2.2960931881793...|
|108406.18717509443| 85400.0|[-2.2911020019242...|
+------------------+--------+--------------------+
only showing top 5 rows

Root Mean Squared Error (RMSE) on test data = 52301.85708505782


gb = gbtr_993774bfa8c4
gbModel = GBTRegressionModel (uid=gbtr_993774bfa8c4) with 20 trees
predictions = [features: vector, label: double ... 1 more field]
evaluator = regEval_7fbbc77ed6ec
rmse = 52301.85708505782


52301.85708505782

---
# 6. Hyperparameter tuning
An important task in Machie Learning is model selection, or using data to find the best model or parameters for a given task. This is also called tuning. Tuning may be done for individual Estimators such as LinearRegression, or for entire Pipelines which include multiple algorithms, featurization, and other steps. Users can tune an entire Pipeline at once, rather than tuning each element in the Pipeline separately. MLlib supports model selection tools, such as `CrossValidator`. These tools require the following items:
* Estimator: algorithm or Pipeline to tune (`setEstimator`)
* Set of ParamMaps: parameters to choose from, sometimes called a "parameter grid" to search over (`setEstimatorParamMaps`)
* Evaluator: metric to measure how well a fitted Model does on held-out test data (`setEvaluator`)

`CrossValidator` begins by splitting the dataset into a set of folds, which are used as separate training and test datasets. For example with `k=3` folds, `CrossValidator` will generate 3 (training, test) dataset pairs, each of which uses 2/3 of the data for training and 1/3 for testing. To evaluate a particular `ParamMap`, `CrossValidator` computes the average evaluation metric for the 3 Models produced by fitting the Estimator on the 3 different (training, test) dataset pairs. After identifying the best `ParamMap`, `CrossValidator` finally re-fits the Estimator using the best ParamMap and the entire dataset.

Below, use the `CrossValidator` to select the best Random Forest model. To do so, you need to define a grid of parameters. Let's say we want to do the search among the different number of trees (1, 5, and 10), and different tree depth (5, 10, and 15).

In [33]:
// TODO: Replace <FILL IN> with appropriate code

import org.apache.spark.ml.tuning.ParamGridBuilder
import org.apache.spark.ml.evaluation.RegressionEvaluator
import org.apache.spark.ml.tuning.CrossValidator

val paramGrid = new ParamGridBuilder().addGrid(rf.numTrees, Array(1,5,10)).addGrid(rf.maxDepth, Array(5,10,15)).build()

val evaluator = new RegressionEvaluator().setLabelCol("label").setPredictionCol("prediction").setMetricName("rmse")
val cv = new CrossValidator().setEstimator(new Pipeline().setStages(Array(rf))).setEvaluator(evaluator).setEstimatorParamMaps(paramGrid).setNumFolds(2)
val cvModel = cv.fit(trainSet)

val predictions = cvModel.transform(testSet)
predictions.select("prediction", "label", "features").show(5)

val rmse = evaluator.evaluate(predictions)
println(s"Root Mean Squared Error (RMSE) on test data = $rmse")

+------------------+--------+--------------------+
|        prediction|   label|            features|
+------------------+--------+--------------------+
|180202.35294117648|128900.0|[-2.2960931881793...|
| 71486.79487179486| 68300.0|[-2.2960931881793...|
| 82017.61437908496| 70500.0|[-2.2960931881793...|
|          102575.0| 60000.0|[-2.2960931881793...|
|110371.81300813006| 85400.0|[-2.2911020019242...|
+------------------+--------+--------------------+
only showing top 5 rows

Root Mean Squared Error (RMSE) on test data = 50323.174549712465


paramGrid = 


Array({
	rfr_064687d07a5a-maxDepth: 5,
	rfr_064687d07a5a-numTrees: 1
}, {
	rfr_064687d07a5a-maxDepth: 5,
	rfr_064687d07a5a-numTrees: 5
}, {
	rfr_064687d07a5a-maxDepth: 5,
	rfr_064687d07a5a-numTrees: 10
}, {
	rfr_064687d07a5a-maxDepth: 10,
	rfr_064687d07a5a-numTrees: 1
}, {
	rfr_064687d07a5a-maxDepth: 10,
	rfr_064687d07a5a-numTrees: 5
}, {
	rfr_064687d07a5a-maxDepth: 10,
	rfr_064687d07a5a-numTrees: 10
}, {
	rfr_064687d07a5a-maxDepth: 15,
	rfr_064687d07a5a-numTrees: 1
}, {
	rfr_064687d07a5a-maxDepth: 15,
	rfr_064687d07a5a-numTrees: 5
}, {
	rfr_064687d07a5a-maxDepth: 15,
	rfr_0646...


---
# 7. Custom transformer
At the end of part two, we added extra columns to the `housing` dataset. Here, we are going to implement a Transformer to do the same task. The Transformer should take the name of two input columns `inputCol1` and `inputCol2`, as well as the name of ouput column `outputCol`. It, then, computes `inputCol1` divided by `inputCol2`, and adds its result as a new column to the dataset. The details of the implemeting a custom Tranfomer is explained [here](https://www.oreilly.com/learning/extend-spark-ml-for-your-own-modeltransformer-types). Please read it before before starting to implement it.

First, define the given parameters of the Transformer and implement a method to validate their schemas (`StructType`).

In [34]:
import org.apache.spark.sql.types.{StructField, StructType, DoubleType}
import org.apache.spark.ml.param.{ParamMap, Param, Params}
import org.apache.spark.ml.param

trait MyParams extends Params {
    final val inputCol1 = new Param[String](this, "inputCol1", "The first input column")
    final val inputCol2 = new Param[String](this, "inputCol2", "The second input column")
    final val outputCol = new Param[String](this, "outputCol", "The output column")
    
  protected def validateAndTransformSchema(schema: StructType): StructType = {
    // Check that the input type is a double
    val idx1 = schema.fieldIndex($(inputCol1))
    val idx2 = schema.fieldIndex($(inputCol2))
    val field1 = schema.fields(idx1)
    val field2 = schema.fields(idx2)
    if (field1.dataType != DoubleType) {
        throw new Exception(s"Input1 type ${field1.dataType} did not match input type DoubleType")
    }
    if (field2.dataType != DoubleType) {
        throw new Exception(s"Input2 type ${field2.dataType} did not match input type DoubleType")
    }
    // Add the return field
    schema.add(StructField($(outputCol), DoubleType, false))
  }
}


defined trait MyParams


Then, extend the class `Transformer`, and implement its setter functions for the input and output columns, and call then `setInputCol1`, `setInputCol2`, and `setOutputCol`. Morever, you need to override the methods `copy`, `transformSchema`, and the `transform`. The details of what you need to cover in these methods is given [here](https://www.oreilly.com/learning/extend-spark-ml-for-your-own-modeltransformer-types).

In [35]:
import org.apache.spark.ml.util.Identifiable
import org.apache.spark.ml.Transformer
import org.apache.spark.ml.param.{ParamMap, Param, Params}
import org.apache.spark.sql.{DataFrame, Dataset}
import org.apache.spark.sql.types.StructType
import org.apache.spark.sql.functions.{col, udf}
import org.apache.spark.sql.types.{StructField, StructType, DoubleType}
import org.apache.spark.ml.param.{ParamMap, Param, Params}
import org.apache.spark.ml.param

class MyTransformer(override val uid: String) extends Transformer with MyParams {
    def this() = this(Identifiable.randomUID("configurablewordcount"))
    
    def setInputCol1(value: String): this.type = set(inputCol1, value)
    
    def setInputCol2(value: String): this.type = set(inputCol2, value)
    
    def setOutputCol(value: String): this.type = set(outputCol, value)

    override def copy(extra: ParamMap): MyTransformer = {
        defaultCopy(extra)
    }

    override def transformSchema(schema: StructType): StructType = {
        // Add the return field
        schema.add(StructField($(outputCol), DoubleType, false))
      }
    
    override def transform(dataset: Dataset[_]): DataFrame = {
        dataset.withColumn($(outputCol), col($(inputCol1)) / col($(inputCol2)))
  }
}

defined class MyTransformer


Now, an instance of `MyTransformer`, and set the input columns `total_rooms` and `households`, and the output column `rooms_per_household` and run it over the `housing` dataset.

In [36]:
val myTransformer = new MyTransformer().setInputCol1("total_rooms").setInputCol2("households").setOutputCol("rooms_per_household")

val myDataset = myTransformer.transform(housing).select("rooms_per_household").show(5)

+-------------------+
|rooms_per_household|
+-------------------+
|  6.984126984126984|
|  6.238137082601054|
|  8.288135593220339|
| 5.8173515981735155|
|  6.281853281853282|
+-------------------+
only showing top 5 rows



myTransformer = configurablewordcount_728d3ffbc029


myDataset: Unit = ()


configurablewordcount_728d3ffbc029

---
# 8. Custom estimator (predictor)
Now, it's time to implement your own linear regression with gradient descent algorithm as a brand new Estimator. The whole code of the Estimator is given to you, and you do not need to implement anything. It is just a sample that shows how to build a custom Estimator.

The gradient descent update for linear regression is:
$$
w_{i+1} = w_{i} - \alpha_{i} \sum\limits_{j=1}^n (w_i^\top x_j - y_j)x_j
$$

where $i$ is the iteration number of the gradient descent algorithm, and $j$ identifies the observation. Here, $w$ represents an array of weights that is the same size as the array of features and provides a weight for each of the features when finally computing the label prediction in the form:

$$
prediction = w^\top \cdot\ x
$$

where $w$ is the final array of weights computed by the gradient descent, $x$ is the array of features of the observation point and $prediction$ is the label we predict should be associated to this observation.

The given `Helper` class implements the helper methods:
* `dot`: implements the dot product of two vectors and the dot product of a vector and a scalar
* `sum`: implements addition of two vectors
* `fill`: creates a vector of predefined size and initialize it with the predefined value

What you need to do is to implement the methods of the Linear Regresstion class `LR`, which are
* `rmsd`: computes the Root Mean Square Error of a given RDD of tuples of (label, prediction) using the formula:
$$
rmse = \sqrt{\frac{\sum\limits_{i=1}^n (label - prediction)^2}{n}}
$$
* `gradientSummand`: computes the following formula:
$$
gs_{ij} = (w_i^\top x_j - y_j)x_j
$$
* `gradient`: computes the following formula:
$$
gradient = \sum\limits_{j=1}^n gs_{ij}
$$

In [37]:
import org.apache.spark.ml.linalg.Vector
import org.apache.spark.ml.PredictorParams
import org.apache.spark.ml.param.ParamMap
import org.apache.spark.ml.util._
import org.apache.spark.rdd.RDD
import org.apache.spark.sql.Dataset
import org.apache.spark.sql.functions._
import org.apache.spark.sql.Row
import org.apache.spark.ml.linalg.Vectors
import org.apache.spark.ml.linalg.Matrices
import org.apache.spark.mllib.evaluation.RegressionMetrics
import org.apache.spark.ml.{PredictionModel, Predictor}

case class Instance(label: Double, features: Vector)

object Helper extends Serializable {
  def dot(v1: Vector, v2: Vector): Double = {
    val m = Matrices.dense(1, v1.size, v1.toArray)
    m.multiply(v2).values(0)
  }

  def dot(v: Vector, s: Double): Vector = {
    val baseArray = v.toArray.map(vi => vi * s)
    Vectors.dense(baseArray)
  }

  def sumVectors(v1: Vector, v2: Vector): Vector = {
    val baseArray = ((v1.toArray) zip (v2.toArray)).map { case (val1, val2) => val1 + val2 }
    Vectors.dense(baseArray)
  }

  def fillVector(size: Int, fillVal: Double): Vector = Vectors.dense(Array.fill[Double](size)(fillVal));
}

defined class Instance
defined object Helper


In [38]:
import org.apache.spark.ml.linalg.Vector
import org.apache.spark.ml.PredictorParams
import org.apache.spark.ml.param.ParamMap
import org.apache.spark.ml.util._
import org.apache.spark.rdd.RDD
import org.apache.spark.sql.Dataset
import org.apache.spark.sql.functions._
import org.apache.spark.sql.Row
import org.apache.spark.ml.linalg.Vectors
import org.apache.spark.ml.linalg.Matrices
import org.apache.spark.mllib.evaluation.RegressionMetrics
import org.apache.spark.ml.{PredictionModel, Predictor}

class LR() extends Serializable {
  def calcRMSE(labelsAndPreds: RDD[(Double, Double)]): Double = {
    val regressionMetrics = new RegressionMetrics(labelsAndPreds)
    regressionMetrics.rootMeanSquaredError
  }
  
  def gradientSummand(weights: Vector, lp: Instance): Vector = {
    val mult = (Helper.dot(weights, lp.features) - lp.label)
    val seq = (0 to lp.features.size - 1).map(i => lp.features(i) * mult)
    return Vectors.dense(seq.toArray)
  }
  
  def linregGradientDescent(trainData: RDD[Instance], numIters: Int): (Vector, Array[Double]) = {
    val n = trainData.count()
    val d = trainData.take(1)(0).features.size
    var w = Helper.fillVector(d, 0)
    val alpha = 1.0
    val errorTrain = Array.fill[Double](numIters)(0.0)

    for (i <- 0 until numIters) {
      val labelsAndPredsTrain = trainData.map(lp => (lp.label, Helper.dot(w, lp.features)))
      errorTrain(i) = calcRMSE(labelsAndPredsTrain)

      val gradient = trainData.map(lp => gradientSummand(w, lp)).reduce((v1, v2) => Helper.sumVectors(v1, v2))
      val alpha_i = alpha / (n * scala.math.sqrt(i + 1))
      val wAux = Helper.dot(gradient, (-1) * alpha_i)
      w = Helper.sumVectors(w, wAux)
    }
    (w, errorTrain)
  }
}

defined class LR


In [39]:
import org.apache.spark.ml.linalg.Vector
import org.apache.spark.ml.PredictorParams
import org.apache.spark.ml.param.ParamMap
import org.apache.spark.ml.util._
import org.apache.spark.rdd.RDD
import org.apache.spark.sql.Dataset
import org.apache.spark.sql.functions._
import org.apache.spark.sql.Row
import org.apache.spark.ml.linalg.Vectors
import org.apache.spark.ml.linalg.Matrices
import org.apache.spark.mllib.evaluation.RegressionMetrics
import org.apache.spark.ml.{PredictionModel, Predictor}

abstract class MyLinearModel[FeaturesType, Model <: MyLinearModel[FeaturesType, Model]]
  extends PredictionModel[FeaturesType, Model] {
}

class MyLinearModelImpl(override val uid: String, val weights: Vector, val trainingError: Array[Double])
    extends MyLinearModel[Vector, MyLinearModelImpl] {

  override def copy(extra: ParamMap): MyLinearModelImpl = defaultCopy(extra)

  def predict(features: Vector): Double = {
    println("Predicting")
    val prediction = Helper.dot(weights, features)
    prediction
  }
}

defined class MyLinearModel
defined class MyLinearModelImpl


In [40]:
import org.apache.spark.ml.linalg.Vector
import org.apache.spark.ml.PredictorParams
import org.apache.spark.ml.param.ParamMap
import org.apache.spark.ml.util._
import org.apache.spark.rdd.RDD
import org.apache.spark.sql.Dataset
import org.apache.spark.sql.functions._

import org.apache.spark.sql.Row
import org.apache.spark.ml.linalg.Vectors
import org.apache.spark.ml.linalg.Matrices
import org.apache.spark.mllib.evaluation.RegressionMetrics
import org.apache.spark.ml.{PredictionModel, Predictor}

abstract class MyLinearRegression[
    FeaturesType,
    Learner <: MyLinearRegression[FeaturesType, Learner, Model],
    Model <: MyLinearModel[FeaturesType, Model]]
  extends Predictor[FeaturesType, Learner, Model] {
}

class MyLinearRegressionImpl(override val uid: String)
    extends MyLinearRegression[Vector, MyLinearRegressionImpl, MyLinearModelImpl] {
  def this() = this(Identifiable.randomUID("linReg"))

  override def copy(extra: ParamMap): MyLinearRegressionImpl = defaultCopy(extra)
  
  def train(dataset: Dataset[_]): MyLinearModelImpl = {
    println("Training")

    val numIters = 10

    val instances: RDD[Instance] = dataset.select(
      col($(labelCol)), col($(featuresCol))).rdd.map {
        case Row(label: Double, features: Vector) =>
          Instance(label, features)
      }

    val (weights, trainingError) = new LR().linregGradientDescent(instances, numIters)

    new MyLinearModelImpl(uid, weights, trainingError)
  }
}

defined class MyLinearRegression
defined class MyLinearRegressionImpl


In [41]:
import org.apache.spark.ml.evaluation.RegressionEvaluator

val lr = new MyLinearRegressionImpl().setLabelCol("label").setFeaturesCol("features")
val model = lr.fit(trainSet)
val predictions = model.transform(trainSet)
predictions.select("prediction", "label", "features").show(5)

// Select (prediction, true label) and compute test error.
val evaluator = new RegressionEvaluator().setLabelCol("label").setPredictionCol("prediction").setMetricName("rmse")
val rmse = evaluator.evaluate(predictions)
println(s"Root Mean Squared Error (RMSE) on test data = $rmse")

Training
+------------------+--------+--------------------+
|        prediction|   label|            features|
+------------------+--------+--------------------+
|150494.48368162982| 94600.0|[-2.3859345407710...|
| 56437.01326906367| 85800.0|[-2.3609786094955...|
| 94650.49480452253|103600.0|[-2.3609786094955...|
|119673.62236257708| 79000.0|[-2.3460050507303...|
|129149.04112136319|111400.0|[-2.3410138644752...|
+------------------+--------+--------------------+
only showing top 5 rows

Root Mean Squared Error (RMSE) on test data = 92437.08933163692


lr = linReg_5930a7ab035c
model = linReg_5930a7ab035c
predictions = [features: vector, label: double ... 1 more field]
evaluator = regEval_049cbe4498eb
rmse = 92437.08933163692


92437.08933163692

---
# 9. An End-to-End Classification Test
As the last step, you are given a dataset called `data/ccdefault.csv`. The dataset represents default of credit card clients. It has 30,000 cases and 24 different attributes. More details about the dataset is available at `data/ccdefault.txt`. In this task you should make three models, compare their results and conclude the ideal solution. Here are the suggested steps:
1. Load the data.
2. Carry out some exploratory analyses (e.g., how various features and the target variable are distributed).
3. Train a model to predict the target variable (risk of `default`).
  - Employ three different models (logistic regression, decision tree, and random forest).
  - Compare the models' performances (e.g., AUC).
  - Defend your choice of best model (e.g., what are the strength and weaknesses of each of these models?).
4. What more would you do with this data? Anything to help you devise a better solution?

### Load the data

In [42]:
// %AddDeps org.vegas-viz vegas_2.11 0.3.11 --transitive
// %AddDeps org.vegas-viz vegas-spark_2.11 0.3.11

Name: Syntax Error.
Message: 
StackTrace: 

In [43]:
// implicit val render = vegas.render.ShowHTML(kernel.display.content("text/html", _))
// import vegas.sparkExt._
// import vegas._

Name: Syntax Error.
Message: 
StackTrace: 

In [44]:
val df = spark.read.format("csv").option("inferSchema", "true").option("header", "true").load("data/ccdefault.csv")

df = [ID: int, LIMIT_BAL: int ... 23 more fields]


[ID: int, LIMIT_BAL: int ... 23 more fields]

In [45]:
df.printSchema()

root
 |-- ID: integer (nullable = true)
 |-- LIMIT_BAL: integer (nullable = true)
 |-- SEX: integer (nullable = true)
 |-- EDUCATION: integer (nullable = true)
 |-- MARRIAGE: integer (nullable = true)
 |-- AGE: integer (nullable = true)
 |-- PAY_0: integer (nullable = true)
 |-- PAY_2: integer (nullable = true)
 |-- PAY_3: integer (nullable = true)
 |-- PAY_4: integer (nullable = true)
 |-- PAY_5: integer (nullable = true)
 |-- PAY_6: integer (nullable = true)
 |-- BILL_AMT1: integer (nullable = true)
 |-- BILL_AMT2: integer (nullable = true)
 |-- BILL_AMT3: integer (nullable = true)
 |-- BILL_AMT4: integer (nullable = true)
 |-- BILL_AMT5: integer (nullable = true)
 |-- BILL_AMT6: integer (nullable = true)
 |-- PAY_AMT1: integer (nullable = true)
 |-- PAY_AMT2: integer (nullable = true)
 |-- PAY_AMT3: integer (nullable = true)
 |-- PAY_AMT4: integer (nullable = true)
 |-- PAY_AMT5: integer (nullable = true)
 |-- PAY_AMT6: integer (nullable = true)
 |-- DEFAULT: integer (nullable = tru

In [46]:
df.count()

30000

In [47]:
df.head(5)

Array([1,20000,2,2,1,24,2,2,-1,-1,-2,-2,3913,3102,689,0,0,0,0,689,0,0,0,0,1], [2,120000,2,2,2,26,-1,2,0,0,0,2,2682,1725,2682,3272,3455,3261,0,1000,1000,1000,0,2000,1], [3,90000,2,2,2,34,0,0,0,0,0,0,29239,14027,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000,0], [4,50000,2,2,1,37,0,0,0,0,0,0,46990,48233,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000,0], [5,50000,1,2,1,57,-1,0,-1,0,0,0,8617,5670,35835,20940,19146,19131,2000,36681,10000,9000,689,679,0])

In [48]:
%%dataframe
df

ID LIMIT_BAL SEX EDUCATION MARRIAGE AGE PAY_0 PAY_2 PAY_3 PAY_4 PAY_5 PAY_6 BILL_AMT1 BILL_AMT2 BILL_AMT3 BILL_AMT4 BILL_AMT5 BILL_AMT6 PAY_AMT1 PAY_AMT2 PAY_AMT3 PAY_AMT4 PAY_AMT5 PAY_AMT6 DEFAULT 1 20000 2 2 1 24 2 2 -1 -1 -2 -2 3913 3102 689 0 0 0 0 689 0 0 0 0 1 2 120000 2 2 2 26 -1 2 0 0 0 2 2682 1725 2682 3272 3455 3261 0 1000 1000 1000 0 2000 1 3 90000 2 2 2 34 0 0 0 0 0 0 29239 14027 13559 14331 14948 15549 1518 1500 1000 1000 1000 5000 0 4 50000 2 2 1 37 0 0 0 0 0 0 46990 48233 49291 28314 28959 29547 2000 2019 1200 1100 1069 1000 0 5 50000 1 2 1 57 -1 0 -1 0 0 0 8617 5670 35835 20940 19146 19131 2000 36681 10000 9000 689 679 0 6 50000 1 1 2 37 0 0 0 0 0 0 64400 57069 57608 19394 19619 20024 2500 1815 657 1000 1000 800 0 7 500000 1 1 2 29 0 0 0 0 0 0 367965 412023 445007 542653 483003 473944 55000 40000 38000 20239 13750 13770 0 8 100000 2 2 2 23 0 -1 -1 0 0 -1 11876 380 601 221 -159 567 380 601 0 581 1687 1542 0 9 140000 2 3 1 28 0 0 2 0 0 0 11285 14096 12108 12211 11793 3719 3329 0 432 1000 1000 1000 0 10 20000 1 3 2 35 -2 -2 -2 -2 -1 -1 0 0 0 0 13007 13912 0 0 0 13007 1122 0 0

### EDA

#### General check

In [49]:
df.describe().show()

+-------+-----------------+------------------+------------------+------------------+------------------+-----------------+------------------+--------------------+------------------+--------------------+------------------+-----------------+-----------------+-----------------+-----------------+------------------+-----------------+----------------+-----------------+------------------+-----------------+------------------+------------------+-----------------+-------------------+
|summary|               ID|         LIMIT_BAL|               SEX|         EDUCATION|          MARRIAGE|              AGE|             PAY_0|               PAY_2|             PAY_3|               PAY_4|             PAY_5|            PAY_6|        BILL_AMT1|        BILL_AMT2|        BILL_AMT3|         BILL_AMT4|        BILL_AMT5|       BILL_AMT6|         PAY_AMT1|          PAY_AMT2|         PAY_AMT3|          PAY_AMT4|          PAY_AMT5|         PAY_AMT6|            DEFAULT|
+-------+-----------------+-----------------

The default decribe function did not provide a clear summary on dataset, it is really hard to read.
Below we start looking at some particular varibles.

In [50]:
for (c <- df.columns) {
    print(s"#(Nulls) in col $c: ")
    println(df.where(df.col(c).isNull).count)
}

#(Nulls) in col ID: 0
#(Nulls) in col LIMIT_BAL: 0
#(Nulls) in col SEX: 0
#(Nulls) in col EDUCATION: 0
#(Nulls) in col MARRIAGE: 0
#(Nulls) in col AGE: 0
#(Nulls) in col PAY_0: 0
#(Nulls) in col PAY_2: 0
#(Nulls) in col PAY_3: 0
#(Nulls) in col PAY_4: 0
#(Nulls) in col PAY_5: 0
#(Nulls) in col PAY_6: 0
#(Nulls) in col BILL_AMT1: 0
#(Nulls) in col BILL_AMT2: 0
#(Nulls) in col BILL_AMT3: 0
#(Nulls) in col BILL_AMT4: 0
#(Nulls) in col BILL_AMT5: 0
#(Nulls) in col BILL_AMT6: 0
#(Nulls) in col PAY_AMT1: 0
#(Nulls) in col PAY_AMT2: 0
#(Nulls) in col PAY_AMT3: 0
#(Nulls) in col PAY_AMT4: 0
#(Nulls) in col PAY_AMT5: 0
#(Nulls) in col PAY_AMT6: 0
#(Nulls) in col DEFAULT: 0


In [51]:
print("Sex-----------------------------------------------------------------------")
df.groupBy("sex").count.show
print("Edu-----------------------------------------------------------------------")
df.groupBy("education").count.show
print("Mar-----------------------------------------------------------------------")
df.groupBy("marriage").count.show
print("DEF-----------------------------------------------------------------------")
df.groupBy("DEFAULT").count.show
print("Age-----------------------------------------------------------------------")
df.select("age").distinct.count

Sex-----------------------------------------------------------------------+---+-----+
|sex|count|
+---+-----+
|  1|11888|
|  2|18112|
+---+-----+

Edu-----------------------------------------------------------------------+---------+-----+
|education|count|
+---------+-----+
|        1|10585|
|        6|   51|
|        3| 4917|
|        5|  280|
|        4|  123|
|        2|14030|
|        0|   14|
+---------+-----+

Mar-----------------------------------------------------------------------+--------+-----+
|marriage|count|
+--------+-----+
|       1|13659|
|       3|  323|
|       2|15964|
|       0|   54|
+--------+-----+

DEF-----------------------------------------------------------------------+-------+-----+
|DEFAULT|count|
+-------+-----+
|      1| 6636|
|      0|23364|
+-------+-----+

Age-----------------------------------------------------------------------

56

In [52]:
//check range of age, mean of age
df.select(max("age"), min("age"), avg("age")).show()

+--------+--------+--------+
|max(age)|min(age)|avg(age)|
+--------+--------+--------+
|      79|      21| 35.4855|
+--------+--------+--------+



In [53]:
val count_ages = df.groupBy("age").count().sort(desc("count")).show(56)
// Vegas("test").withDataFrame(count_ages).encodeX("age", Quantitative, bin=Bin(maxbins=40.0)).encodeY("count", Quantitative).mark(Bar).show

+---+-----+
|age|count|
+---+-----+
| 29| 1605|
| 27| 1477|
| 28| 1409|
| 30| 1395|
| 26| 1256|
| 31| 1217|
| 25| 1186|
| 34| 1162|
| 32| 1158|
| 33| 1146|
| 24| 1127|
| 35| 1113|
| 36| 1108|
| 37| 1041|
| 39|  954|
| 38|  944|
| 23|  931|
| 40|  870|
| 41|  824|
| 42|  794|
| 44|  700|
| 43|  670|
| 45|  617|
| 46|  570|
| 22|  560|
| 47|  501|
| 48|  466|
| 49|  452|
| 50|  411|
| 51|  340|
| 53|  325|
| 52|  304|
| 54|  247|
| 55|  209|
| 56|  178|
| 57|  122|
| 58|  122|
| 59|   83|
| 21|   67|
| 60|   67|
| 61|   56|
| 62|   44|
| 64|   31|
| 63|   31|
| 66|   25|
| 65|   24|
| 67|   16|
| 69|   15|
| 70|   10|
| 68|    5|
| 73|    4|
| 75|    3|
| 71|    3|
| 72|    3|
| 79|    1|
| 74|    1|
+---+-----+



count_ages: Unit = ()


In [54]:
df.select("PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6").describe().show

+-------+------------------+--------------------+------------------+--------------------+------------------+-----------------+
|summary|             PAY_0|               PAY_2|             PAY_3|               PAY_4|             PAY_5|            PAY_6|
+-------+------------------+--------------------+------------------+--------------------+------------------+-----------------+
|  count|             30000|               30000|             30000|               30000|             30000|            30000|
|   mean|           -0.0167|-0.13376666666666667|           -0.1662|-0.22066666666666668|           -0.2662|          -0.2911|
| stddev|1.1238015279973335|  1.1971859730345495|1.1968675684465686|  1.1691386224023357|1.1331874060027525|1.149987625607897|
|    min|                -2|                  -2|                -2|                  -2|                -2|               -2|
|    max|                 8|                   8|                 8|                   8|                 8|   

In [55]:
// check the zero/negative value proportions in all pay
for (i <- List("PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6")){
    println(i+" - 0: "+df.filter(col(i)===0).count)
    println(i+" - -2: "+df.filter(col(i)=== -2).count)
    //println(i+" - >9: "+df.filter(col(i)>9).count)
    
//     val pplot = df.groupBy(i).count()
//     Vegas("test").withDataFrame(pplot).encodeX(i, Quantitative).encodeY("count", Quantitative).mark(Bar).show
    
}

PAY_0 - 0: 14737
PAY_0 - -2: 2759
PAY_2 - 0: 15730
PAY_2 - -2: 3782
PAY_3 - 0: 15764
PAY_3 - -2: 4085
PAY_4 - 0: 16455
PAY_4 - -2: 4348
PAY_5 - 0: 16947
PAY_5 - -2: 4546
PAY_6 - 0: 16286
PAY_6 - -2: 4895


In [56]:
// check the zero/negative value proportions in all Bill_AMT
for (i <- List("BILL_AMT1", "BILL_AMT2", "BILL_AMT3", "BILL_AMT4", "BILL_AMT5", "BILL_AMT6")){
    println(i+"<0 : "+df.filter(col(i)<0).count)
    
    /*val mx = df.select(max("BILL_AMT1")).collect()(0).getInt(0)
    val mn = df.select(min("BILL_AMT1")).collect()(0).getInt(0)
    val tst = (mn to mx by 100).toList
    
    //var pplot = df.filter(col(i)<0)
    var pplot = df.withColumn(i+"_bin", tst.view.find(_ > df(i)))*/

    //Vegas("test").withDataFrame(df).encodeX(i, Quantitative, bin=Bin(maxbins=20.0)).encodeY(aggregate=AggOps.Count, field="*", dataType=Quantitative).mark(Bar).show
}

BILL_AMT1<0 : 590
BILL_AMT2<0 : 669
BILL_AMT3<0 : 655
BILL_AMT4<0 : 675
BILL_AMT5<0 : 655
BILL_AMT6<0 : 688


In [57]:
df.select("BILL_AMT1", "BILL_AMT2", "BILL_AMT3", "BILL_AMT4", "BILL_AMT5", "BILL_AMT6").describe().show

+-------+-----------------+-----------------+-----------------+------------------+-----------------+----------------+
|summary|        BILL_AMT1|        BILL_AMT2|        BILL_AMT3|         BILL_AMT4|        BILL_AMT5|       BILL_AMT6|
+-------+-----------------+-----------------+-----------------+------------------+-----------------+----------------+
|  count|            30000|            30000|            30000|             30000|            30000|           30000|
|   mean|       51223.3309|49179.07516666667|       47013.1548| 43262.94896666666|40311.40096666667|      38871.7604|
| stddev|73635.86057552966|71173.76878252832|69349.38742703677|64332.856133916444|60797.15577026471|59554.1075367459|
|    min|          -165580|           -69777|          -157264|           -170000|           -81334|         -339603|
|    max|           964511|           983931|          1664089|            891586|           927171|          961664|
+-------+-----------------+-----------------+-----------

In [58]:
// check the zero/negative value proportions in all PAY_AMT
for (i <- List("PAY_AMT1", "PAY_AMT2", "PAY_AMT3", "PAY_AMT4", "PAY_AMT5", "PAY_AMT6"))
    println(df.filter(col(i)<=0).count)

5249
5396
5968
6408
6703
7173


In [59]:
df.select("PAY_AMT1", "PAY_AMT2", "PAY_AMT3", "PAY_AMT4", "PAY_AMT5", "PAY_AMT6").describe().show

+-------+-----------------+------------------+-----------------+------------------+------------------+-----------------+
|summary|         PAY_AMT1|          PAY_AMT2|         PAY_AMT3|          PAY_AMT4|          PAY_AMT5|         PAY_AMT6|
+-------+-----------------+------------------+-----------------+------------------+------------------+-----------------+
|  count|            30000|             30000|            30000|             30000|             30000|            30000|
|   mean|        5663.5805|         5921.1635|        5225.6815| 4826.076866666666| 4799.387633333334|5215.502566666667|
| stddev|16563.28035402577|23040.870402057186|17606.96146980311|15666.159744032062|15278.305679144742|17777.46577543531|
|    min|                0|                 0|                0|                 0|                 0|                0|
|    max|           873552|           1684259|           896040|            621000|            426529|           528666|
+-------+-----------------+-----

In [60]:
df.select("DEFAULT").describe().show

+-------+-------------------+
|summary|            DEFAULT|
+-------+-------------------+
|  count|              30000|
|   mean|             0.2212|
| stddev|0.41506180569093254|
|    min|                  0|
|    max|                  1|
+-------+-------------------+



In [61]:
df.select("LIMIT_BAL").describe().show
// Vegas("test").withDataFrame(df).encodeX("LIMIT_BAL", Quantitative, bin=Bin(maxbins=20.0)).encodeY(aggregate=AggOps.Count, field="*", dataType=Quantitative).mark(Bar).show


+-------+------------------+
|summary|         LIMIT_BAL|
+-------+------------------+
|  count|             30000|
|   mean|167484.32266666667|
| stddev|129747.66156720246|
|    min|             10000|
|    max|           1000000|
+-------+------------------+



From the executions above, we notice that:

Age starts from 21 till 79, there are 56 different ages. avg age is 35.48

Higher proportion of people 29-37 years, a few of people falls in 59-79, and 21

Higher proportion of females, 2 types (1 = male; 2 = female)

Higher proportion of edu 1 or 2, 7 types educations.

Higher proportion of single, 4 type marital status.

Higher proportion of zero or negative PAY_0,2,3,4,5,6 variables

Low proportion of zero or negative BILL_AMT_1,2,3,4,5,6 variables

Low proportion of zero or negative PAY_AMT_1,2,3,4,5,6 variables, and there are quite a lot undocumented 0 and -2 values

DEFAULT variables is really unbalanced, we have 6636 for label 1 and 23364 for label 0. We did not do a power analysis thus we cannot simply re-balance the data. There are algorithms for synthetic rebalancing like SMOTE and ADASYN. Both of them are implemented with some python or R packages. But there is no such a implementation for scala and we are ruuning short in time to create the algorithm and run it. But they can help us to improve the training result for sure.


### For categorical type

#### Repayment Status (PAY_X): 
According to the description, this PAY_X is a set of categorical variables with the levels: -1=pay duly, 1=payment delay for one month, 2=payment delay for two months, … 8=payment delay for eight months, 9=payment delay for nine months and above. We observe undocumented values for repayment status variables: -2 and 0. Moreover, fraction of it is quite high (check the result above). We believe it is missing data or NAs. There are many possible ways can solve this problem. 

(1) We can just remove NA observations, but give the consideration that there are 20000+ from all 30000 observations, it is bad practice to remove them. 

(2) Impute with major class. However, again there are 20000+ from all 30000 observations, which is the major class.

(3) Best thing to do it to perform a power analysis (significance level, Type I/II errors and the effect size) on the varibles to check if they can be just removed. However, we did not find the functions from the lib and we believe it will be too much for writing function on our own. 

In the end, we deciced that we do nothing with it

#### Marriage Status, Education, and Sex
Both varibles of Marriage Status, Education have a same problem: there are undocumented value 0, we will impute them with majors as they really only take a small proportion to the entire data. Apart from that Education also has undocument value 5, and 6, we will put them as value 4, which means others. As we mentioned above, there are more females in the dataset.

In [62]:
val fixmardf = df.withColumn("MARRIAGE", when(col("MARRIAGE") === 0,2).otherwise(col("MARRIAGE")))
fixmardf.groupBy("MARRIAGE").count.show

+--------+-----+
|MARRIAGE|count|
+--------+-----+
|       1|13659|
|       3|  323|
|       2|16018|
+--------+-----+



fixmardf = [ID: int, LIMIT_BAL: int ... 23 more fields]


[ID: int, LIMIT_BAL: int ... 23 more fields]

In [63]:
val fixedudf1 = fixmardf.withColumn("EDUCATION", when(col("EDUCATION") === 0,2).otherwise(col("EDUCATION")))
val fixedudf = fixedudf1.withColumn("EDUCATION", when(col("EDUCATION") === 5 || col("EDUCATION") === 6, 4).otherwise(col("education")))
fixedudf.groupBy("EDUCATION").count.show

+---------+-----+
|EDUCATION|count|
+---------+-----+
|        1|10585|
|        3| 4917|
|        4|  454|
|        2|14044|
+---------+-----+



fixedudf1 = [ID: int, LIMIT_BAL: int ... 23 more fields]
fixedudf = [ID: int, LIMIT_BAL: int ... 23 more fields]


[ID: int, LIMIT_BAL: int ... 23 more fields]

### For numerical type

#### Age
Age starts from 21 till 79, there are 56 different ages. avg age is 35.48 Higher proportion of people 29-37 years, a few of people falls in 59-79, and 21.


#### Amount of Previous Payment (PAY_AMTX), Bill Statement (BILL_AMTX), and Limit of Balance (LIMIT_BAL)
Age starts from 21 till 79, there are 56 different ages. avg age is 35.48 Higher proportion of people 29-37 years, a few of people falls in 59-79, and 21.

We made a plot for these variables with pandas and seaborn, noticing there are might be outliers. we decided to perform a outlier test and remove those outliers.


### Correlation

In [64]:
val df_va = new VectorAssembler().setInputCols(df.columns).setOutputCol("df_corl_attri")

val df_Attrs = df_va.transform(df)

df_Attrs.show(5)

+---+---------+---+---------+--------+---+-----+-----+-----+-----+-----+-----+---------+---------+---------+---------+---------+---------+--------+--------+--------+--------+--------+--------+-------+--------------------+
| ID|LIMIT_BAL|SEX|EDUCATION|MARRIAGE|AGE|PAY_0|PAY_2|PAY_3|PAY_4|PAY_5|PAY_6|BILL_AMT1|BILL_AMT2|BILL_AMT3|BILL_AMT4|BILL_AMT5|BILL_AMT6|PAY_AMT1|PAY_AMT2|PAY_AMT3|PAY_AMT4|PAY_AMT5|PAY_AMT6|DEFAULT|       df_corl_attri|
+---+---------+---+---------+--------+---+-----+-----+-----+-----+-----+-----+---------+---------+---------+---------+---------+---------+--------+--------+--------+--------+--------+--------+-------+--------------------+
|  1|    20000|  2|        2|       1| 24|    2|    2|   -1|   -1|   -2|   -2|     3913|     3102|      689|        0|        0|        0|       0|     689|       0|       0|       0|       0|      1|[1.0,20000.0,2.0,...|
|  2|   120000|  2|        2|       2| 26|   -1|    2|    0|    0|    0|    2|     2682|     1725|     2682|    

df_va = vecAssembler_e4eeede34671
df_Attrs = [ID: int, LIMIT_BAL: int ... 24 more fields]


[ID: int, LIMIT_BAL: int ... 24 more fields]

In [65]:
val Row(coeff: Matrix) = Correlation.corr(df_Attrs, "df_corl_attri").head

println(s"The standard correlation coefficient:\n ${coeff}")

The standard correlation coefficient:
 1.0                     0.026179157746199246  ... (25 total)
0.026179157746199246    1.0                   ...
0.018497494176216264    0.024755235111645853  ...
0.03917673481156041     -0.2191606982292233   ...
-0.02907942531876594    -0.10813941027800818  ...
0.018677734490348097    0.14471279755736938   ...
-0.030574932272971585   -0.27121433213471846  ...
-0.01121486826234242    -0.2963821009964793   ...
-0.01849355375769931    -0.2861229539031139   ...
-0.0027348897819585508  -0.2674600096393908   ...
-0.02219923187001884    -0.24941139482410882  ...
-0.02027013406721332    -0.23519539948542625  ...
0.019388673917612936    0.28542986496499084   ...
0.017981897457702494    0.27831436399776227   ...
0.02435405001883995     0.283235783581682     ...
0.04035060294250819     0.2939876237159879    ...
0.016705303156357654    0.29556233765823553   ...
0.016729618316252175    0.2903889506479471    ...
0.009742443464324053    0.19523591523220815   ...


coeff = 


1.0                     0.026179157746199246  ... (25 total)
0.026179157746199246    1.0                   ...
0.018497494176216264    0.024755235111645853  ...
0.03917673481156041     -0.2191606982292233   ...
-0.02907942531876594    -0.10813941027800818  ...
0.018677734490348097    0.14471279755736938   ...
-0.030574932272971585   -0.27121433213471846  ...
-0.01121486826234242    -0.2963821009964793   ...
-0.01849355375769931    -0.2861229539031139   ...
-0.0027348897819585508  -0.2674600096393908   ...
-0.02219923187001884    -0.24941139482410882  ...
-0.02027013406721332    -0.23519539948542625  ...
0.019388673917612936    0.28542986496499084   ...
0.017981897457702494    0.27831436399776227   ...
0.02435405001883995     0.283235783581682  ...


The print matrix is really hard to check, we visualize the result:

<img src="img/corr.png">

We see a high level of linear correlations between the amount of bill statements in different months, and PAY_X variables are highly correlated as well. We might need to think about potential multicollinearity issues, we may need to use some regularisations to create a penalised regression model.

### Preps for learning models

##### Remove outliers

Using IQR with UB = Q_3 + 1.5IQR and LB = Q1 - 1.5IQR

In [66]:
//No negative values for PAY_AMTX, so only upper bound

for(p <- Array("PAY_AMT1","PAY_AMT2","PAY_AMT3","PAY_AMT4","PAY_AMT5","PAY_AMT6")){
    val quantiles = fixedudf.stat.approxQuantile(p, Array(0.25,0.75),0.0)
    val Q1 = quantiles(0)
    val Q3 = quantiles(1)
    val IQR = Q3 - Q1
    // val lowerRange = Q1 - 1.5*IQR
    val upperRange = Q3 + 1.5*IQR
    println(p+"upperRange: "+upperRange)
}

PAY_AMT1upperRange: 11015.0
PAY_AMT2upperRange: 11250.5
PAY_AMT3upperRange: 10677.5
PAY_AMT4upperRange: 9588.5
PAY_AMT5upperRange: 9701.0
PAY_AMT6upperRange: 9824.5


In [67]:
val outliers1 = fixedudf.filter(fixedudf("PAY_AMT1") < 11015 && fixedudf("PAY_AMT2") < 11250.5 && fixedudf("PAY_AMT3") < 10677.5 &&
                               fixedudf("PAY_AMT4") < 9588.5 && fixedudf("PAY_AMT5") < 9701.0 && fixedudf("PAY_AMT6") < 9824.5)

outliers1 = [ID: int, LIMIT_BAL: int ... 23 more fields]


[ID: int, LIMIT_BAL: int ... 23 more fields]

In [68]:
//negative values for BILL_AMTX, so both upper bound
for(p <- Array("BILL_AMT1","BILL_AMT2","BILL_AMT3","BILL_AMT4","BILL_AMT5","BILL_AMT6")){
    val quantiles = fixedudf.stat.approxQuantile(p, Array(0.25,0.75),0.0)
    val Q1 = quantiles(0)
    val Q3 = quantiles(1)
    val IQR = Q3 - Q1
    val lowerRange = Q1 - 1.5*IQR
    val upperRange = Q3 + 1.5*IQR
    println(p+"upperRange: "+upperRange+" lowerRange: "+lowerRange)
}

BILL_AMT1upperRange: 162388.0 lowerRange: -91740.0
BILL_AMT2upperRange: 155534.0 lowerRange: -88546.0
BILL_AMT3upperRange: 146414.0 lowerRange: -83586.0
BILL_AMT4upperRange: 132768.5 lowerRange: -75939.5
BILL_AMT5upperRange: 122818.0 lowerRange: -70870.0
BILL_AMT6upperRange: 121106.0 lowerRange: -70654.0


In [69]:
val outliers2 = outliers1.filter(fixedudf("BILL_AMT1") < 162388 && fixedudf("BILL_AMT2") < 155534 && fixedudf("BILL_AMT3") < 146414 &&
                               fixedudf("BILL_AMT4") < 132768.5 && fixedudf("BILL_AMT5") < 122818 && fixedudf("BILL_AMT6") < 121106)

val outliers3 = outliers2.filter(fixedudf("BILL_AMT1") > -91740 && fixedudf("BILL_AMT2") > -88546 && fixedudf("BILL_AMT3") > -83586 &&
                               fixedudf("BILL_AMT4") > -75939.5 && fixedudf("BILL_AMT5") > -70870 && fixedudf("BILL_AMT6") > -70654)

outliers2 = [ID: int, LIMIT_BAL: int ... 23 more fields]
outliers3 = [ID: int, LIMIT_BAL: int ... 23 more fields]


[ID: int, LIMIT_BAL: int ... 23 more fields]

In [70]:
val quantiles = fixedudf.stat.approxQuantile("LIMIT_BAL", Array(0.25,0.75),0.0)
val Q1 = quantiles(0)
val Q3 = quantiles(1)
val IQR = Q3 - Q1
val lowerRange = Q1 - 1.5*IQR
val upperRange = Q3 + 1.5*IQR
println("Limit of Balance upperRange: "+upperRange+" lowerRange: "+lowerRange)
val nooutliers = outliers3.filter(fixedudf("LIMIT_BAL") > lowerRange && fixedudf("LIMIT_BAL") < upperRange)

Limit of Balance upperRange: 525000.0 lowerRange: -235000.0


quantiles = Array(50000.0, 240000.0)
Q1 = 50000.0
Q3 = 240000.0
IQR = 190000.0
lowerRange = -235000.0
upperRange = 525000.0
nooutliers = [ID: int, LIMIT_BAL: int ... 23 more fields]


[ID: int, LIMIT_BAL: int ... 23 more fields]

before proceeding next step, we rename PAY_0 to PAY_1

In [71]:
val ndflr = nooutliers.withColumnRenamed("PAY_0", "PAY_1")

val ndf = df.withColumnRenamed("PAY_0", "PAY_1")

ndflr = [ID: int, LIMIT_BAL: int ... 23 more fields]
ndf = [ID: int, LIMIT_BAL: int ... 23 more fields]


[ID: int, LIMIT_BAL: int ... 23 more fields]

In [72]:
val noid = ndflr.drop("ID")
val newdf1 = noid.withColumn("PAY_1_C", when($"PAY_1" === -2, 0).otherwise($"PAY_1" + 1))
val newdf2 = newdf1.withColumn("PAY_2_C", when($"PAY_2" === -2, 0).otherwise($"PAY_2" + 1))
val newdf3 = newdf2.withColumn("PAY_3_C", when($"PAY_3" === -2, 0).otherwise($"PAY_3" + 1))
val newdf4 = newdf3.withColumn("PAY_4_C", when($"PAY_4" === -2, 0).otherwise($"PAY_4" + 1))
val newdf5 = newdf4.withColumn("PAY_5_C", when($"PAY_5" === -2, 0).otherwise($"PAY_5" + 1))
val nicedflr = newdf5.withColumn("PAY_6_C", when($"PAY_6" === -2, 0).otherwise($"PAY_6" + 1))

val nicedfdt = ndf.drop("ID")
                

// label columns
val clabel = "DEFAULT"

// categorical columns
val cCatlr = Array("SEX", "EDUCATION", "MARRIAGE", "PAY_1_C", "PAY_2_C", "PAY_3_C", "PAY_4_C", 
                 "PAY_5_C", "PAY_6_C")

val cCatdt = Array("SEX", "education", "marriage", "PAY_1", "PAY_2", "PAY_3", "PAY_4", 
                  "PAY_5", "PAY_6")

// numerical columns
val cNumlr = nicedflr.columns.filter(_ != clabel).filter(!cCatlr.contains(_))
val cNumdt = nicedfdt.columns.filter(_ != clabel).filter(!cCatdt.contains(_))


noid = [LIMIT_BAL: int, SEX: int ... 22 more fields]
newdf1 = [LIMIT_BAL: int, SEX: int ... 23 more fields]
newdf2 = [LIMIT_BAL: int, SEX: int ... 24 more fields]
newdf3 = [LIMIT_BAL: int, SEX: int ... 25 more fields]
newdf4 = [LIMIT_BAL: int, SEX: int ... 26 more fields]
newdf5 = [LIMIT_BAL: int, SEX: int ... 27 more fields]
nicedflr = [LIMIT_BAL: int, SEX: int ... 28 more fields]
nicedfdt = [LIMIT_BAL: int, SEX: int ... 22 more fields]
clabel = DEFAULT
cCatlr = Array(SEX, EDUCATION, MARRIAGE, PAY_1_C, PAY_2_C, ...


Array(SEX, EDUCATION, MARRIAGE, PAY_1_C, PAY_2_C, ...

One Hot encode the categorical types for binarization

In [73]:
val nice_encoderlr = new OneHotEncoderEstimator().setInputCols(cCatlr).setOutputCols(Array("SEX_e", "EDUCATION_e", "MARRIAGE_e", "PAY_1_e", "PAY_2_e", "PAY_3_e", "PAY_4_e", 
                 "PAY_5_e", "PAY_6_e"))
val nice_encodedlr = nice_encoderlr.fit(nicedflr).transform(nicedflr)


nice_encoderlr = oneHotEncoder_0ac8fbf46899
nice_encodedlr = [LIMIT_BAL: int, SEX: int ... 37 more fields]


[LIMIT_BAL: int, SEX: int ... 37 more fields]

In [74]:
val nice_encoderdt = new OneHotEncoderEstimator().setInputCols(Array("SEX", "EDUCATION", "MARRIAGE")).setOutputCols(Array("SEX_e", "EDUCATION_e", "MARRIAGE_e"))
val nice_encodeddt = nice_encoderdt.fit(nicedfdt).transform(nicedfdt)

nice_encoderdt = oneHotEncoder_3e3253e36389
nice_encodeddt = [LIMIT_BAL: int, SEX: int ... 25 more fields]


[LIMIT_BAL: int, SEX: int ... 25 more fields]

Normalize the numerical types

In [75]:
val scalerVectorAssemblerlr = new VectorAssembler().setInputCols(cNumlr).setOutputCol("scale")
val niceFeaturesForScalerlr = scalerVectorAssemblerlr.transform(nice_encodedlr)
val niceScalerlr = new StandardScaler().setInputCol("scale").setOutputCol("rescaled")
val niceScaledlr = niceScalerlr.fit(niceFeaturesForScalerlr).transform(niceFeaturesForScalerlr)



scalerVectorAssemblerlr = vecAssembler_9cfec7f83862
niceFeaturesForScalerlr = [LIMIT_BAL: int, SEX: int ... 38 more fields]
niceScalerlr = stdScal_49f368f52938
niceScaledlr = [LIMIT_BAL: int, SEX: int ... 39 more fields]


[LIMIT_BAL: int, SEX: int ... 39 more fields]

In [76]:
val scalerVectorAssemblerdt = new VectorAssembler().setInputCols(cNumdt).setOutputCol("scale")
val niceFeaturesForScalerdt = scalerVectorAssemblerdt.transform(nice_encodeddt)
val niceScalerdt = new StandardScaler().setInputCol("scale").setOutputCol("rescaled")
val niceScaleddt = niceScalerdt.fit(niceFeaturesForScalerdt).transform(niceFeaturesForScalerdt)

scalerVectorAssemblerdt = vecAssembler_8242f82e9bf7
niceFeaturesForScalerdt = [LIMIT_BAL: int, SEX: int ... 26 more fields]
niceScalerdt = stdScal_88ff653abc07
niceScaleddt = [LIMIT_BAL: int, SEX: int ... 27 more fields]


[LIMIT_BAL: int, SEX: int ... 27 more fields]

In [77]:
val input_featureslr = Array("rescaled", "SEX_e", "EDUCATION_e", "MARRIAGE_e", "PAY_1_e", "PAY_2_e", "PAY_3_e", "PAY_4_e", 
                 "PAY_5_e", "PAY_6_e")
val niceVectorAssemblerlr = new VectorAssembler().setInputCols(input_featureslr).setOutputCol("features")
val im_datasetlr = niceVectorAssemblerlr.transform(niceScaledlr).select("features", "DEFAULT")
val lrdataset = im_datasetlr.withColumnRenamed("DEFAULT","label")


input_featureslr = Array(rescaled, SEX_e, EDUCATION_e, MARRIAGE_e, PAY_1_e, PAY_2_e, PAY_3_e, PAY_4_e, PAY_5_e, PAY_6_e)
niceVectorAssemblerlr = vecAssembler_dddc156edab1
im_datasetlr = [features: vector, DEFAULT: int]
lrdataset = [features: vector, label: int]


[features: vector, label: int]

In [78]:
val input_featuresdt = Array("rescaled", "SEX_e", "EDUCATION_e", "MARRIAGE_e", "PAY_1", "PAY_2", "PAY_3", "PAY_4", 
                 "PAY_5", "PAY_6")
val niceVectorAssemblerdt = new VectorAssembler().setInputCols(input_featuresdt).setOutputCol("features")
val im_datasetdt = niceVectorAssemblerdt.transform(niceScaleddt).select("features", "DEFAULT")
val dtdataset = im_datasetdt.withColumnRenamed("DEFAULT","label")

input_featuresdt = Array(rescaled, SEX_e, EDUCATION_e, MARRIAGE_e, PAY_1, PAY_2, PAY_3, PAY_4, PAY_5, PAY_6)
niceVectorAssemblerdt = vecAssembler_fd9f505e5b97
im_datasetdt = [features: vector, DEFAULT: int]
dtdataset = [features: vector, label: int]


[features: vector, label: int]

In [79]:
lrdataset.printSchema()
lrdataset.count

root
 |-- features: vector (nullable = true)
 |-- label: integer (nullable = true)



19730

In [80]:
dtdataset.printSchema()
dtdataset.count

root
 |-- features: vector (nullable = true)
 |-- label: integer (nullable = true)



30000

In [81]:
val Array(lrtrainSet, lrtestSet) = lrdataset.randomSplit(Array(0.8, 0.2))
val Array(dttrainSet, dttestSet) = dtdataset.randomSplit(Array(0.8, 0.2))

lrtrainSet = [features: vector, label: int]
lrtestSet = [features: vector, label: int]
dttrainSet = [features: vector, label: int]
dttestSet = [features: vector, label: int]


[features: vector, label: int]

Below we start training at testing the data:

Our approach are from 2 different methods. First we directly train/test lr, dt, rf on balanced data. Second we train/test lr, dt, rf with re-balanced data

Note that, as we mentioned above there are outilers in numerical type, we also compared the performance of the models using the dataset with/without outliers. It turns out lr works better without outliers but dt and rf works better with outliers in the dataset

On the other hand, having an imbalanced dataset means there are difference between the number of examples for positve and negative classes and this gap is huge. Therefore we should use f1 score rather than ROC/AUC. 

In [82]:
import org.apache.spark.ml.classification.LogisticRegression
import org.apache.spark.ml.evaluation.BinaryClassificationEvaluator

// train the model
val cclr = new LogisticRegression().setFeaturesCol("features").setLabelCol("label")
val cclrModel = cclr.fit(lrtrainSet)
val cclrPredictions = cclrModel.transform(lrtestSet)
val cctrainingSummary = cclrModel.summary

val e = new BinaryClassificationEvaluator()
val accroc = e.evaluate(cclrPredictions)
println("Roc on Testset:"+accroc)

cclrPredictions.select("prediction", "rawPrediction", "label", "features").show(5)

println(s"Coefficients: " + cclrModel.coefficients + s", Intercept: " + cclrModel.intercept)



Roc on Testset:0.783291819398069
+----------+--------------------+-----+--------------------+
|prediction|       rawPrediction|label|            features|
+----------+--------------------+-----+--------------------+
|       0.0|[1.26354397230741...|    0|(83,[0,1,2,3,4,5,...|
|       0.0|[1.63375107737277...|    0|(83,[0,1,2,3,4,5,...|
|       0.0|[1.00513759396117...|    1|(83,[0,1,2,3,4,5,...|
|       0.0|[1.66824430969039...|    0|(83,[0,1,2,3,4,5,...|
|       0.0|[1.53191155801042...|    0|(83,[0,1,2,3,4,5,...|
+----------+--------------------+-----+--------------------+
only showing top 5 rows

Coefficients: [-0.15873502018503002,0.01993224829445545,0.35309661056931146,-0.33255423771100756,0.2949613344033097,-0.14011200004101512,-0.003622818601259447,-0.08941125963804532,-0.22657229002681423,0.1146394348528074,0.23981459736411004,-0.036516255896807695,-0.33052286813309234,0.3319988663509582,-0.13093166967870265,-0.10287820632714104,-0.11179111481589886,-0.051925279868820465,-0.035

cclr = logreg_9cee1786f81f
cclrModel = logreg_9cee1786f81f
cclrPredictions = [features: vector, label: int ... 3 more fields]
cctrainingSummary = org.apache.spark.ml.classification.BinaryLogisticRegressionTrainingSummaryImpl@315fa822
e = binEval_5434cb986a9d
accroc = 0.783291819398069


0.783291819398069

In [83]:
import org.apache.spark.ml.classification.{BinaryLogisticRegressionSummary, LogisticRegression}
val cctrainingSummary = cclrModel.binarySummary
val ccobjectiveHistory = cctrainingSummary.objectiveHistory
val roc = cctrainingSummary.roc
roc.show()
println(s"areaUnderROC: ${cctrainingSummary.areaUnderROC}")

+--------------------+-------------------+
|                 FPR|                TPR|
+--------------------+-------------------+
|                 0.0|                0.0|
|0.002481177275838467|0.03143418467583497|
|0.004534565366187543|0.06409626719056974|
|0.007186858316221766|0.09528487229862476|
|0.010609171800136893|0.12401768172888016|
|0.014801505817932922| 0.1505402750491159|
|0.018908281998631076|0.17730844793713163|
|0.022501711156741957| 0.2055500982318271|
|0.026950718685831623|  0.231335952848723|
| 0.03148528405201916| 0.2568762278978389|
|0.036019849418206705| 0.2824165029469548|
| 0.04106776180698152|0.30648330058939094|
| 0.04654346338124572| 0.3293222003929273|
|0.051420260095824774|0.35388015717092336|
| 0.05843600273785079|0.37229862475442044|
|  0.0646817248459959| 0.3929273084479371|
| 0.07221081451060918|0.40987229862475444|
| 0.07931211498973306|0.42804518664047153|
| 0.08667008898015058| 0.4454813359528487|
| 0.09428473648186174|0.46218074656188607|
+----------

cctrainingSummary = org.apache.spark.ml.classification.BinaryLogisticRegressionTrainingSummaryImpl@315fa822
ccobjectiveHistory = Array(0.5713510156448334, 0.501396902589193, 0.49305864039966124, 0.4896216773642506, 0.48172117187415214, 0.47827458755353286, 0.4752162855852714, 0.4743984062242194, 0.47362347546962963, 0.47301892994035116, 0.4726723205398575, 0.4723973040178922, 0.47229347419400175, 0.4721923270191548, 0.47211784870042156, 0.47205352630614006, 0.4720097653076546, 0.4719732769703551, 0.47191891041576267, 0.47183224171020377, 0.47180223443805247, 0.4717661618839973, 0.4717079790799982, 0.471...


Array(0.5713510156448334, 0.501396902589193, 0.49305864039966124, 0.4896216773642506, 0.48172117187415214, 0.47827458755353286, 0.4752162855852714, 0.4743984062242194, 0.47362347546962963, 0.47301892994035116, 0.4726723205398575, 0.4723973040178922, 0.47229347419400175, 0.4721923270191548, 0.47211784870042156, 0.47205352630614006, 0.4720097653076546, 0.4719732769703551, 0.47191891041576267, 0.47183224171020377, 0.47180223443805247, 0.4717661618839973, 0.4717079790799982, 0.471...

In [84]:
import org.apache.spark.ml.tuning.ParamGridBuilder
import org.apache.spark.ml.evaluation.BinaryClassificationEvaluator
import org.apache.spark.ml.evaluation.MulticlassClassificationEvaluator

import org.apache.spark.ml.tuning.CrossValidator

val cclrParamGrid = new ParamGridBuilder()
    .addGrid(cclr.regParam, Array(0,0.01, 0.1, 0.5)).addGrid(cclr.elasticNetParam, Array(0, 0.001, 0.01, 0.1))
    .build()

val cclrEvaluator = new BinaryClassificationEvaluator()
val cclrf1Evaluator = new MulticlassClassificationEvaluator().setMetricName("f1").setLabelCol("label").setPredictionCol("prediction")


val cclrCv = new CrossValidator()
    .setEstimator(cclr)
    .setEvaluator(cclrf1Evaluator)
    .setEstimatorParamMaps(cclrParamGrid)
    .setNumFolds(4)

val cclrCvModel = cclrCv.fit(lrtrainSet)

val cclrPredictions = cclrCvModel.transform(lrtestSet)
cclrPredictions.select("prediction", "label", "features").show(5)

val cclrAuc = cclrEvaluator.evaluate(cclrPredictions)
println(s"Area Under ROC (AUC) on test data = "+cclrAuc)

val cclrf1Auc = cclrf1Evaluator.evaluate(cclrPredictions)
println(s"F1 on test data = "+cclrf1Auc)



+----------+-----+--------------------+
|prediction|label|            features|
+----------+-----+--------------------+
|       0.0|    0|(83,[0,1,2,3,4,5,...|
|       0.0|    0|(83,[0,1,2,3,4,5,...|
|       0.0|    1|(83,[0,1,2,3,4,5,...|
|       0.0|    0|(83,[0,1,2,3,4,5,...|
|       0.0|    0|(83,[0,1,2,3,4,5,...|
+----------+-----+--------------------+
only showing top 5 rows

Area Under ROC (AUC) on test data = 0.783291819398069
F1 on test data = 0.7724418482316683


cclrParamGrid = 


Array({
	logreg_9cee1786f81f-elasticNetParam: 0.0,
	logreg_9cee1786f81f-regParam: 0.0
}, {
	logreg_9cee1786f81f-elasticNetParam: 0.001,
	logreg_9cee1786f81f-regParam: 0.0
}, {
	logreg_9cee1786f81f-elasticNetParam: 0.01,
	logreg_9cee1786f81f-regParam: 0.0
}, {
	logreg_9cee1786f81f-elasticNetParam: 0.1,
	logreg_9cee1786f81f-regParam: 0.0
}, {
	logreg_9cee1786f81f-elasticNetParam: 0.0,
	logreg_9cee1786f81f-regParam: 0.01
}, {
	logreg_9cee1786f81f-elasticNetParam: 0.001,
	logreg_9cee1786f81f-regPa...


In [85]:
import org.apache.spark.ml.classification.DecisionTreeClassifier

val ccdt = new DecisionTreeClassifier().setFeaturesCol("features").setLabelCol("label")
val ccdtModel = ccdt.fit(dttrainSet)

val ccdtPredictions1 = ccdtModel.transform(dttestSet)
ccdtPredictions1.select("prediction", "rawPrediction", "label", "features").show(5)

val evaluator = new BinaryClassificationEvaluator()
val f1Evaluator = new MulticlassClassificationEvaluator().setMetricName("f1").setLabelCol("label").setPredictionCol("prediction")

val accuracy = evaluator.evaluate(ccdtPredictions1)


val ccdtParamGrid = new ParamGridBuilder().addGrid(ccdt.maxDepth, Array(5,10,15)).build()

val ccdtCv = new CrossValidator().setEstimator(ccdt).setEvaluator(f1Evaluator).setEstimatorParamMaps(ccdtParamGrid).setNumFolds(4)

val ccdtCvModel = ccdtCv.fit(dttrainSet)

val ccdtPredictions = ccdtCvModel.transform(dttestSet)
cclrPredictions.select("prediction", "label", "features").show(5)

val ccdtAuc = evaluator.evaluate(ccdtPredictions)
println(s"Area Under ROC (AUC) on test data = "+ccdtAuc)

val ccdtf1Auc = f1Evaluator.evaluate(ccdtPredictions)
println(s"F1 on test data = "+ccdtf1Auc)


+----------+--------------+-----+--------------------+
|prediction| rawPrediction|label|            features|
+----------+--------------+-----+--------------------+
|       0.0|[3012.0,609.0]|    0|(33,[0,1,2,3,4,5,...|
|       0.0|[3012.0,609.0]|    1|(33,[0,1,2,3,4,5,...|
|       0.0|[1870.0,350.0]|    0|(33,[0,1,2,3,4,5,...|
|       0.0|[3012.0,609.0]|    0|(33,[0,1,2,3,4,5,...|
|       0.0|[3012.0,609.0]|    0|(33,[0,1,2,3,4,5,...|
+----------+--------------+-----+--------------------+
only showing top 5 rows

+----------+-----+--------------------+
|prediction|label|            features|
+----------+-----+--------------------+
|       0.0|    0|(83,[0,1,2,3,4,5,...|
|       0.0|    0|(83,[0,1,2,3,4,5,...|
|       0.0|    1|(83,[0,1,2,3,4,5,...|
|       0.0|    0|(83,[0,1,2,3,4,5,...|
|       0.0|    0|(83,[0,1,2,3,4,5,...|
+----------+-----+--------------------+
only showing top 5 rows

Area Under ROC (AUC) on test data = 0.3729709452504132
F1 on test data = 0.8035952205311429


ccdt = dtc_7b9a14b83550
ccdtModel = DecisionTreeClassificationModel (uid=dtc_7b9a14b83550) of depth 5 with 61 nodes
ccdtPredictions1 = [features: vector, label: int ... 3 more fields]
evaluator = binEval_21fb7d732e4c
f1Evaluator = mcEval_81b0a195901f
accuracy = 0.3729709452504132
ccdtParamGrid = 


Array({
	dtc_7b9a14b83550-maxDepth: 5
}, {
	dtc_7b9a14b83550-maxDepth: 10
}, {
	dtc_7b9a14b83550-...


In [86]:
import org.apache.spark.ml.regression.RandomForestRegressor
import org.apache.spark.ml.evaluation.RegressionEvaluator
import org.apache.spark.ml.classification.{RandomForestClassificationModel, RandomForestClassifier}


val rf = new RandomForestClassifier().setLabelCol("label").setFeaturesCol("features")

// train the model
val rfMdel = rf.fit(dttrainSet)

// make predictions on the test data
val predictions = rfMdel.transform(dttestSet)
predictions.select("prediction", "label", "features").show(5)

// select (prediction, true label) and compute test error
val rfEvaluator = new BinaryClassificationEvaluator()
val rff1Evaluator = new MulticlassClassificationEvaluator().setMetricName("f1").setLabelCol("label").setPredictionCol("prediction")

val accuracy = evaluator.evaluate(predictions)
///

val rfParamGrid = new ParamGridBuilder().addGrid(rf.numTrees, Array(2,5,15)).addGrid(rf.maxDepth, Array(5,10,15)).addGrid(rf.maxBins, Array(20,40,80)).build()

val rfCv = new CrossValidator().setEstimator(rf).setEvaluator(rff1Evaluator).setEstimatorParamMaps(rfParamGrid).setNumFolds(4)

val rfModel = rfCv.fit(dttrainSet)

val rfPredictions = rfModel.transform(dttestSet)
cclrPredictions.select("prediction", "label", "features").show(5)

val rfAuc = evaluator.evaluate(rfPredictions)
println(s"Area Under ROC (AUC) on test data = $rfAuc")

val rff1 = rff1Evaluator.evaluate(rfPredictions)
println(s"F1 on test data = "+rff1)



+----------+-----+--------------------+
|prediction|label|            features|
+----------+-----+--------------------+
|       0.0|    0|(33,[0,1,2,3,4,5,...|
|       0.0|    1|(33,[0,1,2,3,4,5,...|
|       0.0|    0|(33,[0,1,2,3,4,5,...|
|       0.0|    0|(33,[0,1,2,3,4,5,...|
|       0.0|    0|(33,[0,1,2,3,4,5,...|
+----------+-----+--------------------+
only showing top 5 rows

+----------+-----+--------------------+
|prediction|label|            features|
+----------+-----+--------------------+
|       0.0|    0|(83,[0,1,2,3,4,5,...|
|       0.0|    0|(83,[0,1,2,3,4,5,...|
|       0.0|    1|(83,[0,1,2,3,4,5,...|
|       0.0|    0|(83,[0,1,2,3,4,5,...|
|       0.0|    0|(83,[0,1,2,3,4,5,...|
+----------+-----+--------------------+
only showing top 5 rows

Area Under ROC (AUC) on test data = 0.7673904385510164
F1 on test data = 0.8012631531566016


rf = rfc_062f01cff07f
rfMdel = RandomForestClassificationModel (uid=rfc_062f01cff07f) with 20 trees
predictions = [features: vector, label: int ... 3 more fields]
rfEvaluator = binEval_6b3ea73faef6
rff1Evaluator = mcEval_cc326f32176e
accuracy = 0.7648912217100706


rfParamGrid: Array[o...


0.7648912217100706

In [87]:
def balanceDataset(dataset: DataFrame): DataFrame = {
    val numNegatives = dataset.filter(dataset("label") === 0).count
    val datasetSize = dataset.count
    val balancingRatio = (datasetSize - numNegatives).toDouble / datasetSize

    val calculateWeights = udf { d: Double =>
      if (d == 0.0) {
        1 * balancingRatio
      }
      else {
        (1 * (1.0 - balancingRatio))
      }
    }

    val weightedDataset = dataset.withColumn("classWeightCol", calculateWeights(dataset("label")))
    weightedDataset
  }

balanceDataset: (dataset: org.apache.spark.sql.DataFrame)org.apache.spark.sql.DataFrame


In [88]:
val lrccd = balanceDataset(lrdataset)
val dtccd = balanceDataset(dtdataset)

lrccd = [features: vector, label: int ... 1 more field]
dtccd = [features: vector, label: int ... 1 more field]


[features: vector, label: int ... 1 more field]

In [89]:
lrccd.groupBy("classWeightCol").count.show
dtccd.groupBy("classWeightCol").count.show

+------------------+-----+
|    classWeightCol|count|
+------------------+-----+
|0.2587430309173847|14625|
|0.7412569690826153| 5105|
+------------------+-----+

+------------------+-----+
|    classWeightCol|count|
+------------------+-----+
|            0.2212|23364|
|0.7787999999999999| 6636|
+------------------+-----+



In [90]:
val Array(lrtrainSetb, lrtestSetb) = lrccd.randomSplit(Array(0.8, 0.2))
val Array(dttrainSetb, dttestSetb) = dtccd.randomSplit(Array(0.8, 0.2))

lrtrainSetb = [features: vector, label: int ... 1 more field]
lrtestSetb = [features: vector, label: int ... 1 more field]
dttrainSetb = [features: vector, label: int ... 1 more field]
dttestSetb = [features: vector, label: int ... 1 more field]


[features: vector, label: int ... 1 more field]

In [91]:
// train the model
val blr = new LogisticRegression().setWeightCol("classWeightCol").setFeaturesCol("features").setLabelCol("label")
val blrModel = blr.fit(lrtrainSetb)
val blrPredictions = blrModel.transform(lrtestSetb)
val blrtrainingSummary = blrModel.summary

val be = new BinaryClassificationEvaluator()
val baccroc = be.evaluate(blrPredictions)
println("Roc on Testset:"+baccroc)

blrPredictions.select("prediction", "rawPrediction", "label", "features").show(5)
println(s"Coefficients: " + blrModel.coefficients + s", Intercept: " + blrModel.intercept)

Roc on Testset:0.7557376114248563
+----------+--------------------+-----+--------------------+
|prediction|       rawPrediction|label|            features|
+----------+--------------------+-----+--------------------+
|       0.0|[1.76391891576466...|    0|(83,[0,1,2,3,4,5,...|
|       0.0|[0.66437378126421...|    1|(83,[0,1,2,3,4,5,...|
|       0.0|[2.02792722104051...|    1|(83,[0,1,2,3,4,5,...|
|       1.0|[-0.0086199047306...|    0|(83,[0,1,2,3,4,5,...|
|       0.0|[0.06063635762236...|    0|(83,[0,1,2,3,4,5,...|
+----------+--------------------+-----+--------------------+
only showing top 5 rows

Coefficients: [-0.1557532136272973,0.038299868143563454,0.38667827573911,-0.257132593892431,0.1830821051673794,-0.17535564453153352,-0.10116721831742936,0.07339339842931887,-0.3696293968334926,0.2802555597141934,0.28693688369923503,-0.1016688809849575,-0.3735161999398396,0.3802735949008777,-0.15679192675670192,-0.10369266837761161,-0.07760349825736196,-0.07212900476231367,-0.04474392020552

blr = logreg_acdec88aa181
blrModel = logreg_acdec88aa181
blrPredictions = [features: vector, label: int ... 4 more fields]
blrtrainingSummary = org.apache.spark.ml.classification.BinaryLogisticRegressionTrainingSummaryImpl@21e61b21
be = binEval_016f578593c2
baccroc = 0.7557376114248563


0.7557376114248563

In [92]:
val blrtrainingSummary = blrModel.binarySummary
val blrobjectiveHistory = blrtrainingSummary.objectiveHistory
val blrroc = blrtrainingSummary.roc
blrroc.show()
println(s"areaUnderROC: ${blrtrainingSummary.areaUnderROC}")

+--------------------+--------------------+
|                 FPR|                 TPR|
+--------------------+--------------------+
|                 0.0|                 0.0|
|0.002473769512923313|0.031204290589956118|
|0.004862236628849271| 0.06265236470014628|
|0.007336006141772584| 0.09385665529010238|
|0.010662799624669454| 0.12286689419795221|
|0.014074895504563678|   0.151389566065334|
|0.017231084193465838| 0.18064358849341786|
|0.020813784867354773| 0.20867869332033154|
|0.025676021496204043| 0.23305704534373475|
| 0.02925872217009298| 0.26109215017064846|
|0.035229889959907876| 0.28230131643100925|
| 0.03992152179476243| 0.30716723549488056|
|0.044954363217606416|  0.3310580204778157|
| 0.05032841422843982|  0.3539736713798147|
| 0.05578776763627058|  0.3766455387615797|
| 0.06329437857203787| 0.39346660165772795|
| 0.06952145355284484| 0.41394441735738663|
| 0.07626034291563592| 0.43295953193564113|
| 0.08282862748443232|  0.4524622135543637|
| 0.09050584321419432| 0.4692832

blrtrainingSummary = org.apache.spark.ml.classification.BinaryLogisticRegressionTrainingSummaryImpl@21e61b21
blrobjectiveHistory = Array(0.6931464400907618, 0.6106810357275432, 0.602037097271954, 0.5872031261914947, 0.5849838976894195, 0.5814145088028945, 0.5773479590768626, 0.5708420443351456, 0.5693658553660935, 0.5678514418543684, 0.5675230323366365, 0.5671639190429918, 0.5666525595852653, 0.5660862699949594, 0.5655432286462271, 0.565300736597443, 0.5650961786388028, 0.564946113865516, 0.5648338416616837, 0.5646719250899007, 0.5646259792168999, 0.5644129492912243, 0.5643681524749418, 0.5642134799735498, 0.5640717010902843, 0.5639606840736265, 0.5638602020780602, 0.5637540600614317, 0.5636777242...


Array(0.6931464400907618, 0.6106810357275432, 0.602037097271954, 0.5872031261914947, 0.5849838976894195, 0.5814145088028945, 0.5773479590768626, 0.5708420443351456, 0.5693658553660935, 0.5678514418543684, 0.5675230323366365, 0.5671639190429918, 0.5666525595852653, 0.5660862699949594, 0.5655432286462271, 0.565300736597443, 0.5650961786388028, 0.564946113865516, 0.5648338416616837, 0.5646719250899007, 0.5646259792168999, 0.5644129492912243, 0.5643681524749418, 0.5642134799735498, 0.5640717010902843, 0.5639606840736265, 0.5638602020780602, 0.5637540600614317, 0.5636777242...

In [93]:
val blrParamGrid = new ParamGridBuilder()
    .addGrid(blr.regParam, Array(0,0.01, 0.1, 0.5)).addGrid(blr.elasticNetParam, Array(0, 0.001, 0.01, 0.1))
    .build()

val blrEvaluator = new BinaryClassificationEvaluator()
val blrf1Evaluator = new MulticlassClassificationEvaluator().setMetricName("f1").setLabelCol("label").setPredictionCol("prediction")

val blrCv = new CrossValidator()
    .setEstimator(blr)
    .setEvaluator(blrf1Evaluator)
    .setEstimatorParamMaps(blrParamGrid)
    .setNumFolds(4)

val blrCvModel = blrCv.fit(lrtrainSetb)

val blrPredictions = blrCvModel.transform(lrtestSetb)
blrPredictions.select("prediction", "label", "features").show(5)

val blrAuc = blrEvaluator.evaluate(blrPredictions)
println(s"Area Under ROC (AUC) on test data = "+blrAuc)

val rff1 = blrf1Evaluator.evaluate(blrPredictions)
println(s"F1 on test data = "+rff1)

+----------+-----+--------------------+
|prediction|label|            features|
+----------+-----+--------------------+
|       0.0|    0|(83,[0,1,2,3,4,5,...|
|       0.0|    1|(83,[0,1,2,3,4,5,...|
|       0.0|    1|(83,[0,1,2,3,4,5,...|
|       0.0|    0|(83,[0,1,2,3,4,5,...|
|       0.0|    0|(83,[0,1,2,3,4,5,...|
+----------+-----+--------------------+
only showing top 5 rows

Area Under ROC (AUC) on test data = 0.7468964574230428
F1 on test data = 0.7635258054997512


blrParamGrid = 


Array({
	logreg_acdec88aa181-elasticNetParam: 0.0,
	logreg_acdec88aa181-regParam: 0.0
}, {
	logreg_acdec88aa181-elasticNetParam: 0.001,
	logreg_acdec88aa181-regParam: 0.0
}, {
	logreg_acdec88aa181-elasticNetParam: 0.01,
	logreg_acdec88aa181-regParam: 0.0
}, {
	logreg_acdec88aa181-elasticNetParam: 0.1,
	logreg_acdec88aa181-regParam: 0.0
}, {
	logreg_acdec88aa181-elasticNetParam: 0.0,
	logreg_acdec88aa181-regParam: 0.01
}, {
	logreg_acdec88aa181-elasticNetParam: 0.001,
	logreg_acdec88aa181-regParam: 0.01
}, {
	logreg_acdec88aa181-elasticNetParam: 0.01,
	logreg_acdec88aa181-regParam: 0.01
}, {
	logreg_acdec88aa181-elasticNetParam: 0.1,
	logreg_acdec88aa181-regParam: 0.01
}, {
	logreg_acdec88aa181-elasticNetParam: 0.0,
	logreg_acdec8...


Best LR f1 score = 0.7724418482316683

Best DT f1 score = 0.8035952205311429

Best RF f1 score = 0.8012631531566016

ROC curve is not a good metric for highly imbalanced data, because the False Positive Rate ( False Positives / Total Real Negatives ) does not drop drastically when the total real negatives is huge.

Whereas Precision ( True Positives / (True Positives + False Positives) ) is highly sensitive to False Positives and is not impacted by a large total real negative denominator.

There are two interesting aspects of this dataset:

1. There are outliers in numerical data from the statisical test. From our experiments, it seemed that it has an impact on lr result.

2. The dataset is imbalanced, the best approach should be using SMOTE or adasyn to perform a synthetic upsampling, however there is no such lib in scala and we are short in time to create the algorithm. Therefore we invented a sloppy weight changing algorithm to rebalance the training by controling the weight.

Note: if we look at the AUC score, RF is better than DT. However as we argued that the dataset is imbalanced, it is not a good practice to use the AUC score for measuring.

We would choose DT if we do not perform any outlier removal and dataset rebalancing.